In [ ]:
import pandas as pd
path = r"C:\Users\lamin\OneDrive\Documents\Maitrise en info Canada\ASTD project\data\ASTD_area_level3_201902.csv"

df = pd.read_csv(path, sep=";", low_memory=False)

df.head(10)

:

:

In [1]:
import track_builder as tb

files = [r"C:\Users\lamin\OneDrive\Documents\Maitrise en info Canada\ASTD project\data\ASTD_area_level3_201901.csv",
         r"C:\Users\lamin\OneDrive\Documents\Maitrise en info Canada\ASTD project\data\ASTD_area_level3_201902.csv"]

df = tb.load_astd_data(files[0])

df.head(5)

Loading ASTD CSVs: 100%|██████████| 1/1 [01:53<00:00, 113.53s/it]
c:\Users\lamin\OneDrive\Documents\Maitrise en info Canada\ASTD project\TrackBuilder\track_builder\core\io_helpers.py:143: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  df["month"] = df["date_time_utc"].dt.to_period("M").astype(str)

,shipid,date_time_utc,flagname,iceclass,astd_cat,sizegroup_gt,fuelquality,fuelcons,co,co2,...,organiccarbon,oilbilgewater,blackwater,greywater,garbage,dist_nextpoint,sec_nextpoint,longitude,latitude,month
0,162,2019-01-01 00:00:00+00:00,iceland,<NA>,unknown,<NA>,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2.242847,209,-21.827280,64.134210,2019-01
1,385,2019-01-01 00:00:00+00:00,<NA>,<NA>,unknown,<NA>,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2.987542,370,14.245747,67.389120,2019-01
2,3619,2019-01-01 00:00:00+00:00,norway,<NA>,other activities,1000 - 4999 gt,4,0.016730,0.000124,0.053035,...,1.017200e-05,2.720000e-08,0.001281,0.009481,0.0,491.440920,369,14.545295,68.205574,2019-01
3,1645,2019-01-01 00:00:00+00:00,iceland,<NA>,fishing vessels,< 1000 gt,0,0.001227,0.000009,0.003890,...,7.460000e-07,6.400000e-09,0.001170,0.003844,0.0,0.731465,361,-23.703033,64.896220,2019-01
4,2490,2019-01-01 00:00:00+00:00,iceland,<NA>,fishing vessels,1000 - 4999 gt,0,0.000935,0.000007,0.002964,...,5.685000e-07,6.100000e-09,0.000797,0.002619,0.0,2.241636,82,-23.127956,66.069336,2019-01

In [4]:
df

,shipid,date_time_utc,flagname,iceclass,astd_cat,sizegroup_gt,fuelquality,fuelcons,co,co2,...,organiccarbon,oilbilgewater,blackwater,greywater,garbage,dist_nextpoint,sec_nextpoint,longitude,latitude,month
0,162,2019-01-01 00:00:00+00:00,iceland,<NA>,unknown,<NA>,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2.242847,209,-21.827280,64.134210,2019-01
1,385,2019-01-01 00:00:00+00:00,<NA>,<NA>,unknown,<NA>,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2.987542,370,14.245747,67.389120,2019-01
2,3619,2019-01-01 00:00:00+00:00,norway,<NA>,other activities,1000 - 4999 gt,4,0.016730,0.000124,0.053035,...,1.017200e-05,2.720000e-08,0.001281,0.009481,0.0,491.440920,369,14.545295,68.205574,2019-01
3,1645,2019-01-01 00:00:00+00:00,iceland,<NA>,fishing vessels,< 1000 gt,0,0.001227,0.000009,0.003890,...,7.460000e-07,6.400000e-09,0.001170,0.003844,0.0,0.731465,361,-23.703033,64.896220,2019-01
4,2490,2019-01-01 00:00:00+00:00,iceland,<NA>,fishing vessels,1000 - 4999 gt,0,0.000935,0.000007,0.002964,...,5.685000e-07,6.100000e-09,0.000797,0.002619,0.0,2.241636,82,-23.127956,66.069336,2019-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18219900,250,2019-01-31 23:59:57+00:00,<NA>,<NA>,unknown,<NA>,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.916833,249,-20.317630,65.825250,2019-01
18219901,145,2019-01-31 23:59:58+00:00,<NA>,<NA>,unknown,<NA>,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1.117709,202,-14.007736,64.786480,2019-01
18219902,931,2019-01-31 23:59:58+00:00,<NA>,<NA>,unknown,<NA>,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,3.387100,180,17.170370,60.678890,2019-01
18219903,2117,2019-01-31 23:59:58+00:00,iceland,<NA>,other activities,< 1000 gt,0,0.000807,0.000006,0.002558,...,4.907000e-07,6.400000e-09,0.001176,0.003865,0.0,1.346573,363,-23.598950,65.684410,2019-01
18219904,882,2019-01-31 23:59:58+00:00,<NA>,<NA>,unknown,<NA>,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2.373756,370,11.307200,64.912735,2019-01

In [1]:
import track_builder as tb

files = [r"C:\Users\lamin\OneDrive\Documents\Maitrise en info Canada\ASTD project\data\ASTD_area_level3_201901.csv",
         r"C:\Users\lamin\OneDrive\Documents\Maitrise en info Canada\ASTD project\data\ASTD_area_level3_201902.csv"]

df_with_optimized_config = tb.load_astd_data(files[0], use_optimized_config=True)

Loading ASTD CSVs: 100%|██████████| 1/1 [01:30<00:00, 90.88s/it]
c:\Users\lamin\OneDrive\Documents\Maitrise en info Canada\ASTD project\TrackBuilder\track_builder\core\io_helpers.py:143: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  df["month"] = df["date_time_utc"].dt.to_period("M").astype(str)

In [2]:
df_with_optimized_config

,shipid,date_time_utc,flagname,iceclass,astd_cat,sizegroup_gt,dist_nextpoint,sec_nextpoint,longitude,latitude,month
0,162,2019-01-01 00:00:00+00:00,iceland,<NA>,unknown,<NA>,2.242847,209,-21.827280,64.134209,2019-01
1,385,2019-01-01 00:00:00+00:00,<NA>,<NA>,unknown,<NA>,2.987542,370,14.245747,67.389122,2019-01
2,3619,2019-01-01 00:00:00+00:00,norway,<NA>,other activities,1000 - 4999 gt,491.440918,369,14.545295,68.205574,2019-01
3,1645,2019-01-01 00:00:00+00:00,iceland,<NA>,fishing vessels,< 1000 gt,0.731465,361,-23.703033,64.896217,2019-01
4,2490,2019-01-01 00:00:00+00:00,iceland,<NA>,fishing vessels,1000 - 4999 gt,2.241636,82,-23.127956,66.069336,2019-01
...,...,...,...,...,...,...,...,...,...,...,...
18219900,250,2019-01-31 23:59:57+00:00,<NA>,<NA>,unknown,<NA>,0.916833,249,-20.317631,65.825249,2019-01
18219901,145,2019-01-31 23:59:58+00:00,<NA>,<NA>,unknown,<NA>,1.117709,202,-14.007736,64.786484,2019-01
18219902,931,2019-01-31 23:59:58+00:00,<NA>,<NA>,unknown,<NA>,3.387100,180,17.170370,60.678890,2019-01
18219903,2117,2019-01-31 23:59:58+00:00,iceland,<NA>,other activities,< 1000 gt,1.346573,363,-23.598949,65.684410,2019-01
18219904,882,2019-01-31 23:59:58+00:00,<NA>,<NA>,unknown,<NA>,2.373756,370,11.307200,64.912735,2019-01

In [ ]:
import pandas as pd
import os
from pathlib import Path

# 1. define source and destination directories
source_directory = Path(r"C:\Users\lamin\OneDrive\Documents\Maitrise en info Canada\ASTD project\data")
sample_directory = Path(r"C:\Users\lamin\OneDrive\Documents\Maitrise en info Canada\ASTD project\data_sample")

# # 2. create destination directory if it doesn't exist
# sample_directory.mkdir(exist_ok=True)

# print(f"Création des échantillons dans : {sample_directory}")

# # 3. process each CSV file in the source directory
# for file_name in os.listdir(source_directory):
#     if file_name.endswith('.csv'):
#         source_file_path = source_directory / file_name
#         sample_file_path = sample_directory / file_name
        
#         print(f"  -> Traitement de {file_name}...")
        
#         # read a small sample of the CSV file (first 100 rows)
#         df_sample = pd.read_csv(source_file_path, sep=';', nrows=100)
        
#         # write the sample to the new directory
#         # index=False to avoid writing row numbers
#         df_sample.to_csv(sample_file_path, sep=';', index=False)

# print("Sample data created successfully.")

Création des échantillons dans : C:\Users\lamin\OneDrive\Documents\Maitrise en info Canada\ASTD project\data_sample
  -> Traitement de ASTD_area_level3_201901.csv...
  -> Traitement de ASTD_area_level3_201902.csv...
  -> Traitement de ASTD_area_level3_201903.csv...
  -> Traitement de ASTD_area_level3_201904.csv...
  -> Traitement de ASTD_area_level3_201905.csv...
  -> Traitement de ASTD_area_level3_201906.csv...
  -> Traitement de ASTD_area_level3_201907.csv...
  -> Traitement de ASTD_area_level3_201908.csv...
  -> Traitement de ASTD_area_level3_201909.csv...
  -> Traitement de ASTD_area_level3_201910.csv...
  -> Traitement de ASTD_area_level3_201911.csv...
  -> Traitement de ASTD_area_level3_201912.csv...
Terminé ! Votre dossier de test est prêt.

In [ ]:
import track_builder as tb

# use the sample data directory created above
sample_data_path = r"C:\Users\lamin\OneDrive\Documents\Maitrise en info Canada\ASTD project\data_sample"

# Test loading a single sample file
print("Test du chargement de tout le dossier d'échantillons...")
df_all_samples = tb.load_astd_data(sample_data_path)
print(df_all_samples.info())

Test du chargement de tout le dossier d'échantillons...

Loading ASTD CSVs:   0%|          | 0/12 [00:00<?, ?it/s]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   shipid          1200 non-null   int64
 1   date_time_utc   1200 non-null   datetime64[ns, UTC]
 2   flagname        299 non-null    object
 3   iceclass        0 non-null      float64
 4   astd_cat        1200 non-null   object
 5   sizegroup_gt    299 non-null    object
 6   fuelquality     1200 non-null   int64
 7   fuelcons        299 non-null    float64
 8   co              299 non-null    float64
 9   co2             299 non-null    float64
 10  so2             299 non-null    float64
 11  pm              299 non-null    float64
 12  nox             299 non-null    float64
 13  n2o             299 non-null    float64
 14  nmvoc           299 non-null    float64
 15  ch4             299 non-null    float64
 16  blackcarbon     299 non-null    float64
 17  organiccarbon   299 non-null    float64
 18  oilbilgewater   299 non-null    float64
 19  blackwater      299 non-null    float64
 20  greywater       299 non-null    float64
 21  garbage         299 non-null    float64
 22  dist_nextpoint  1050 non-null   float64
 23  sec_nextpoint   1200 non-null   int64
 24  longitude       1200 non-null   float64
 25  latitude        1200 non-null   float64
dtypes: datetime64[ns, UTC](1), float64(19), int64(3), object(3)
memory usage: 243.9+ KB
None

In [ ]:
# Test loading samples for specific months
print("\nTest du chargement des mois de juillet à septembre...")
df_monthly_samples = tb.load_astd_monthly(sample_data_path, year=2019, months=[7, 8, 9])
print(df_monthly_samples.info())

Test du chargement des mois de juillet à septembre...

Loading ASTD CSVs:   0%|          | 0/3 [00:00<?, ?it/s]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   shipid          300 non-null    int64
 1   date_time_utc   300 non-null    datetime64[ns, UTC]
 2   flagname        199 non-null    object
 3   iceclass        0 non-null      float64
 4   astd_cat        300 non-null    object
 5   sizegroup_gt    199 non-null    object
 6   fuelquality     300 non-null    int64
 7   fuelcons        199 non-null    float64
 8   co              199 non-null    float64
 9   co2             199 non-null    float64
 10  so2             199 non-null    float64
 11  pm              199 non-null    float64
 12  nox             199 non-null    float64
 13  n2o             199 non-null    float64
 14  nmvoc           199 non-null    float64
 15  ch4             199 non-null    float64
 16  blackcarbon     199 non-null    float64
 17  organiccarbon   199 non-null    float64
 18  oilbilgewater   199 non-null    float64
 19  blackwater      199 non-null    float64
 20  greywater       199 non-null    float64
 21  garbage         199 non-null    float64
 22  dist_nextpoint  199 non-null    float64
 23  sec_nextpoint   300 non-null    int64
 24  longitude       300 non-null    float64
 25  latitude        300 non-null    float64
dtypes: datetime64[ns, UTC](1), float64(19), int64(3), object(3)
memory usage: 61.1+ KB
None

In [11]:
# --- Setup ---
# Define the path to a single sample file.
single_file = sample_data_path + "/ASTD_area_level3_201909.csv"
print(f"--- Loading a single file: {single_file} ---\n")

# --- Action ---
# Call the function with the single file path.
df_single = tb.load_astd_data(single_file)

# --- Verification ---
# Display the info and the first 5 rows of the resulting DataFrame.
df_single.info()
display(df_single.head())

--- Loading a single file: C:\Users\lamin\OneDrive\Documents\Maitrise en info Canada\ASTD project\data_sample/ASTD_area_level3_201909.csv ---

Loading ASTD CSVs:   0%|          | 0/1 [00:00<?, ?it/s]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   shipid          100 non-null    int64
 1   date_time_utc   100 non-null    datetime64[ns, UTC]
 2   flagname        100 non-null    object
 3   iceclass        0 non-null      float64
 4   astd_cat        100 non-null    object
 5   sizegroup_gt    100 non-null    object
 6   fuelquality     100 non-null    int64
 7   fuelcons        100 non-null    float64
 8   co              100 non-null    float64
 9   co2             100 non-null    float64
 10  so2             100 non-null    float64
 11  pm              100 non-null    float64
 12  nox             100 non-null    float64
 13  n2o             100 non-null    float64
 14  nmvoc           100 non-null    float64
 15  ch4             100 non-null    float64
 16  blackcarbon     100 non-null    float64
 17  organiccarbon   100 non-null    float64
 18  oilbilgewater   100 non-null    float64
 19  blackwater      100 non-null    float64
 20  greywater       100 non-null    float64
 21  garbage         100 non-null    float64
 22  dist_nextpoint  100 non-null    float64
 23  sec_nextpoint   100 non-null    int64
 24  longitude       100 non-null    float64
 25  latitude        100 non-null    float64
dtypes: datetime64[ns, UTC](1), float64(19), int64(3), object(3)
memory usage: 20.4+ KB

,shipid,date_time_utc,flagname,iceclass,astd_cat,sizegroup_gt,fuelquality,fuelcons,co,co2,...,blackcarbon,organiccarbon,oilbilgewater,blackwater,greywater,garbage,dist_nextpoint,sec_nextpoint,longitude,latitude
0,1,2019-09-11 00:03:58+00:00,Norway,NaN,Fishing vessels,< 1000 GT,0,0.001254,0.000009,0.003976,...,2.258000e-07,7.625000e-07,6.500000e-09,0.000427,0.003160,0.000,2.963553,369,25.965061,70.983150
1,1,2019-09-11 00:16:17+00:00,Norway,NaN,Fishing vessels,< 1000 GT,0,0.001227,0.000009,0.003890,...,2.209000e-07,7.460000e-07,6.400000e-09,0.000418,0.003092,0.000,3.161857,361,25.964964,70.983160
2,1,2019-09-11 01:04:49+00:00,Norway,NaN,Fishing vessels,< 1000 GT,0,0.001251,0.000009,0.003965,...,2.251000e-07,7.605000e-07,6.500000e-09,0.000426,0.003152,0.000,1.615317,368,25.965057,70.983116
3,0,2019-09-11 01:12:55+00:00,Norway,NaN,Passenger ships,1000 - 4999 GT,0,0.003517,0.000026,0.011150,...,6.331000e-07,2.138600e-06,1.640000e-08,0.053530,0.396123,0.004,0.000000,370,12.286775,65.969124
4,0,2019-09-11 01:25:15+00:00,Norway,NaN,Passenger ships,1000 - 4999 GT,0,0.003517,0.000026,0.011150,...,6.331000e-07,2.138600e-06,1.640000e-08,0.053530,0.396123,0.004,0.075766,370,12.286774,65.969124

In [12]:
import pandas as pd

df_test = pd.read_csv(single_file, sep=";", low_memory=False)

df_test

,shipid,date_time_utc,flagname,iceclass,astd_cat,sizegroup_gt,fuelquality,fuelcons,co,co2,...,blackcarbon,organiccarbon,oilbilgewater,blackwater,greywater,garbage,dist_nextpoint,sec_nextpoint,longitude,latitude
0,0,2019-09-11 12:49:15,Norway,NaN,Passenger ships,1000 - 4999 GT,0,0.017209,1.273496e-04,0.054554,...,3.097700e-06,1.046340e-05,1.610000e-08,0.052517,0.388628,0.004,2236.542500,363,12.231715,65.924960
1,0,2019-09-11 06:18:44,Norway,NaN,Passenger ships,1000 - 4999 GT,0,0.009873,7.306260e-05,0.031298,...,1.777200e-06,6.003000e-06,1.700000e-08,0.055411,0.410040,0.004,1780.179600,383,12.316360,65.958664
2,0,2019-09-11 03:34:03,Norway,NaN,Passenger ships,1000 - 4999 GT,0,0.003432,2.539610e-05,0.010879,...,6.177000e-07,2.086600e-06,1.600000e-08,0.052228,0.386487,0.004,0.000000,361,12.286767,65.969124
3,0,2019-09-11 01:12:55,Norway,NaN,Passenger ships,1000 - 4999 GT,0,0.003517,2.602930e-05,0.011150,...,6.331000e-07,2.138600e-06,1.640000e-08,0.053530,0.396123,0.004,0.000000,370,12.286775,65.969124
4,0,2019-09-11 21:53:14,Norway,NaN,Passenger ships,1000 - 4999 GT,0,0.003527,2.609960e-05,0.011181,...,6.349000e-07,2.144400e-06,1.640000e-08,0.053675,0.397193,0.004,0.758668,371,12.286775,65.969120
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1,2019-09-11 03:13:07,Norway,NaN,Fishing vessels,< 1000 GT,0,0.001227,9.079800e-06,0.003890,...,2.209000e-07,7.460000e-07,6.400000e-09,0.000418,0.003092,0.000,1.884127,361,25.965015,70.983120
96,1,2019-09-11 18:14:18,Norway,NaN,Fishing vessels,< 1000 GT,0,0.001224,9.054600e-06,0.003879,...,2.202000e-07,7.439000e-07,6.400000e-09,0.000417,0.003083,0.000,253.087770,360,25.087502,71.188860
97,1,2019-09-11 13:58:45,Norway,NaN,Fishing vessels,< 1000 GT,0,0.001234,9.130100e-06,0.003911,...,2.221000e-07,7.501000e-07,6.400000e-09,0.000420,0.003109,0.000,447.042480,363,24.843563,71.177140
98,1,2019-09-11 03:43:26,Norway,NaN,Fishing vessels,< 1000 GT,0,0.000112,8.300000e-07,0.000356,...,2.020000e-08,6.820000e-08,6.000000e-10,0.000038,0.000283,0.000,1.314351,33,25.965070,70.983110
99,1,2019-09-11 10:37:28,Norway,NaN,Fishing vessels,< 1000 GT,0,0.001261,9.331300e-06,0.003997,...,2.270000e-07,7.667000e-07,6.600000e-09,0.000429,0.003178,0.000,1807.547600,371,25.725185,70.936356

In [13]:
# read the file with only the useful columns
df_test_useful = tb.load_astd_data(single_file, usecols="default")

df_test_useful

Loading ASTD CSVs:   0%|          | 0/1 [00:00<?, ?it/s]

,shipid,date_time_utc,flagname,iceclass,astd_cat,sizegroup_gt,dist_nextpoint,sec_nextpoint,longitude,latitude
0,1,2019-09-11 00:03:58+00:00,Norway,NaN,Fishing vessels,< 1000 GT,2.963552,369,25.965061,70.983147
1,1,2019-09-11 00:16:17+00:00,Norway,NaN,Fishing vessels,< 1000 GT,3.161857,361,25.964964,70.983162
2,1,2019-09-11 01:04:49+00:00,Norway,NaN,Fishing vessels,< 1000 GT,1.615317,368,25.965057,70.983116
3,0,2019-09-11 01:12:55+00:00,Norway,NaN,Passenger ships,1000 - 4999 GT,0.000000,370,12.286775,65.969124
4,0,2019-09-11 01:25:15+00:00,Norway,NaN,Passenger ships,1000 - 4999 GT,0.075766,370,12.286774,65.969124
...,...,...,...,...,...,...,...,...,...,...
95,1,2019-09-11 23:12:39+00:00,Norway,NaN,Fishing vessels,< 1000 GT,1706.533569,369,24.527418,71.173164
96,0,2019-09-11 23:30:24+00:00,Norway,NaN,Passenger ships,1000 - 4999 GT,0.075766,360,12.286774,65.969124
97,1,2019-09-11 23:37:16+00:00,Norway,NaN,Fishing vessels,< 1000 GT,1679.302246,361,24.337944,71.178604
98,1,2019-09-11 23:43:18+00:00,Norway,NaN,Fishing vessels,< 1000 GT,1719.325928,370,24.291407,71.179504
99,1,2019-09-11 23:49:28+00:00,Norway,NaN,Fishing vessels,< 1000 GT,700.258606,140,24.243738,71.180305

In [14]:
# read with specified columns
df_test_specified = tb.load_astd_data(single_file, usecols=["shipid", "latitude", "longitude", "date_time_utc"])
df_test_specified

Loading ASTD CSVs:   0%|          | 0/1 [00:00<?, ?it/s]

    shipid             date_time_utc  longitude   latitude
0        1 2019-09-11 00:03:58+00:00  25.965061  70.983150
1        1 2019-09-11 00:16:17+00:00  25.964964  70.983160
2        1 2019-09-11 01:04:49+00:00  25.965057  70.983116
3        0 2019-09-11 01:12:55+00:00  12.286775  65.969124
4        0 2019-09-11 01:25:15+00:00  12.286774  65.969124
..     ...                       ...        ...        ...
95       1 2019-09-11 23:12:39+00:00  24.527418  71.173164
96       0 2019-09-11 23:30:24+00:00  12.286774  65.969124
97       1 2019-09-11 23:37:16+00:00  24.337944  71.178604
98       1 2019-09-11 23:43:18+00:00  24.291407  71.179504
99       1 2019-09-11 23:49:28+00:00  24.243738  71.180305

[100 rows x 4 columns]

In [7]:
# read with a single column
df_single_column = tb.load_astd_data(single_file, usecols=["shipid"])
df_single_column

Loading ASTD CSVs:   0%|          | 0/1 [00:00<?, ?it/s]

INFO: Failed to read with separator ';'. Pandas error: Inference failed, produced a single column.
INFO: Failed to read with separator ','. Pandas error: Usecols do not match columns, columns expected but not found: ['shipid']

ValueError: Could not parse CSV C:\Users\lamin\OneDrive\Documents\Maitrise en info Canada\ASTD project\data_sample\ASTD_area_level3_201909.csv with any tried configuration.

In [15]:
# --- Setup ---
print(f"--- Loading all files from directory: {sample_data_path} ---\n")

# --- Action ---
# Call the function with the directory path.
df_directory = tb.load_astd_data(sample_data_path)

# --- Verification ---
# The resulting DataFrame should contain 1200 rows (12 files * 100 rows).
df_directory.info()

--- Loading all files from directory: C:\Users\lamin\OneDrive\Documents\Maitrise en info Canada\ASTD project\data_sample ---

Loading ASTD CSVs:   0%|          | 0/12 [00:00<?, ?it/s]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   shipid          1200 non-null   int64
 1   date_time_utc   1200 non-null   datetime64[ns, UTC]
 2   flagname        299 non-null    object
 3   iceclass        0 non-null      float64
 4   astd_cat        1200 non-null   object
 5   sizegroup_gt    299 non-null    object
 6   fuelquality     1200 non-null   int64
 7   fuelcons        299 non-null    float64
 8   co              299 non-null    float64
 9   co2             299 non-null    float64
 10  so2             299 non-null    float64
 11  pm              299 non-null    float64
 12  nox             299 non-null    float64
 13  n2o             299 non-null    float64
 14  nmvoc           299 non-null    float64
 15  ch4             299 non-null    float64
 16  blackcarbon     299 non-null    float64
 17  organiccarbon   299 non-null    float64
 18  oilbilgewater   299 non-null    float64
 19  blackwater      299 non-null    float64
 20  greywater       299 non-null    float64
 21  garbage         299 non-null    float64
 22  dist_nextpoint  1050 non-null   float64
 23  sec_nextpoint   1200 non-null   int64
 24  longitude       1200 non-null   float64
 25  latitude        1200 non-null   float64
dtypes: datetime64[ns, UTC](1), float64(19), int64(3), object(3)
memory usage: 243.9+ KB

In [16]:
# --- Setup ---
months_to_load = [1, 6, 7, 12] # January, June, July, December
year_to_load = 2019
print(f"--- Loading months {months_to_load} for year {year_to_load} ---\n")

# --- Action ---
df_specific_months = tb.load_astd_monthly(sample_data_path, year=year_to_load, months=months_to_load, usecols="default")

# --- Verification ---
# The resulting DataFrame should contain 300 rows (3 files * 100 rows).
df_specific_months.info()

df_specific_months.head()

--- Loading months [1, 6, 7, 12] for year 2019 ---

Loading ASTD CSVs:   0%|          | 0/4 [00:00<?, ?it/s]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   shipid          400 non-null    int32
 1   date_time_utc   400 non-null    datetime64[ns, UTC]
 2   flagname        0 non-null      category
 3   iceclass        0 non-null      category
 4   astd_cat        400 non-null    category
 5   sizegroup_gt    0 non-null      category
 6   dist_nextpoint  295 non-null    float32
 7   sec_nextpoint   400 non-null    int32
 8   longitude       400 non-null    float32
 9   latitude        400 non-null    float32
dtypes: category(4), datetime64[ns, UTC](1), float32(3), int32(2)
memory usage: 12.6 KB

,shipid,date_time_utc,flagname,iceclass,astd_cat,sizegroup_gt,dist_nextpoint,sec_nextpoint,longitude,latitude
0,0,2019-01-22 00:01:21+00:00,NaN,NaN,Unknown,NaN,1306.315674,300,24.217222,64.646126
1,0,2019-01-22 00:06:20+00:00,NaN,NaN,Unknown,NaN,1581.733765,360,24.244421,64.647263
2,0,2019-01-22 00:12:21+00:00,NaN,NaN,Unknown,NaN,1342.213379,370,24.277414,64.648369
3,0,2019-01-22 00:18:31+00:00,NaN,NaN,Unknown,NaN,1649.876465,371,24.305347,64.649620
4,0,2019-01-22 00:30:52+00:00,NaN,NaN,Unknown,NaN,1455.400269,370,24.370941,64.658775

In [17]:
# --- Setup ---
print(f"--- Loading the full year 2019 ---\n")

# --- Action ---
df_full_year = tb.load_astd_monthly(sample_data_path, year=2019)

# --- Verification ---
# The resulting DataFrame should contain 1200 rows.
df_full_year.info()

--- Loading the full year 2019 ---

Loading ASTD CSVs:   0%|          | 0/12 [00:00<?, ?it/s]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   shipid          1200 non-null   int64
 1   date_time_utc   1200 non-null   datetime64[ns, UTC]
 2   flagname        299 non-null    object
 3   iceclass        0 non-null      float64
 4   astd_cat        1200 non-null   object
 5   sizegroup_gt    299 non-null    object
 6   fuelquality     1200 non-null   int64
 7   fuelcons        299 non-null    float64
 8   co              299 non-null    float64
 9   co2             299 non-null    float64
 10  so2             299 non-null    float64
 11  pm              299 non-null    float64
 12  nox             299 non-null    float64
 13  n2o             299 non-null    float64
 14  nmvoc           299 non-null    float64
 15  ch4             299 non-null    float64
 16  blackcarbon     299 non-null    float64
 17  organiccarbon   299 non-null    float64
 18  oilbilgewater   299 non-null    float64
 19  blackwater      299 non-null    float64
 20  greywater       299 non-null    float64
 21  garbage         299 non-null    float64
 22  dist_nextpoint  1050 non-null   float64
 23  sec_nextpoint   1200 non-null   int64
 24  longitude       1200 non-null   float64
 25  latitude        1200 non-null   float64
dtypes: datetime64[ns, UTC](1), float64(19), int64(3), object(3)
memory usage: 243.9+ KB

# ----------------------- Testing Sampling ----------------------------------------

In [1]:
import track_builder as tb


# 2) Load with sampling (e.g., 1% of data)
print("\n--- Loading with 1% sampling ---\n")
df = tb.load_astd_data(r"C:\Users\lamin\OneDrive\Documents\Maitrise en info Canada\ASTD project\data", sampling=0.010)

df

--- Loading with 1% sampling ---

Loading ASTD CSVs:   0%|          | 0/12 [00:00<?, ?it/s]

,shipid,date_time_utc,flagname,iceclass,astd_cat,sizegroup_gt,fuelquality,fuelcons,co,co2,...,blackcarbon,organiccarbon,oilbilgewater,blackwater,greywater,garbage,dist_nextpoint,sec_nextpoint,longitude,latitude
0,2724,2019-01-01 00:00:08+00:00,Norway,NaN,Fishing vessels,< 1000 GT,0,NaN,NaN,NaN,...,NaN,NaN,6.600000e-09,0.000429,0.003178,0.000,1.925582,371,29.730220,70.637690
1,7541,2019-01-01 00:00:21+00:00,Bahamas,FS Ice Class 1B,Refrigerated cargo ships,1000 - 4999 GT,3,0.054326,0.000402,0.172214,...,9.778700e-06,3.303020e-05,2.720000e-08,0.001171,0.008668,0.000,2569.820800,368,26.905954,71.196945
2,3477,2019-01-01 00:00:24+00:00,Finland,FS Ice Class 1A Super,Passenger ships,25000 - 49999,2,0.087230,0.000646,0.278918,...,1.570140e-05,5.303590e-05,5.000000e-09,0.036458,0.269792,0.003,807.133600,84,19.825968,59.911163
3,4693,2019-01-01 00:00:49+00:00,Norway,NaN,Passenger ships,1000 - 4999 GT,0,0.006845,0.000051,0.021698,...,1.232100e-06,4.161600e-06,3.190000e-08,0.104167,0.770833,0.008,4.299842,720,6.082797,62.354076
4,6025,2019-01-01 00:01:03+00:00,Norway,NaN,General cargo ships,1000 - 4999 GT,1,0.001943,0.000014,0.006160,...,3.498000e-07,1.181400e-06,2.730000e-08,0.001178,0.008715,0.000,2.456293,370,6.148159,62.469257
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2166220,2300,2019-12-17 23:58:24+00:00,Finland,NaN,Other activities,< 1000 GT,0,0.005586,0.000041,0.017707,...,1.005500e-06,3.396200e-06,6.500000e-09,0.001196,0.003929,0.000,1300.225800,369,28.118185,61.486210
2166221,759,2019-12-17 23:58:36+00:00,NaN,NaN,Unknown,NaN,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.234503,363,13.900329,67.406330
2166222,1610,2019-12-17 23:58:37+00:00,Finland,NaN,Other activities,< 1000 GT,0,0.000291,0.000002,0.000924,...,5.240000e-08,1.771000e-07,6.700000e-09,0.001231,0.004046,0.000,4.130921,380,21.217833,62.378334
2166223,741,2019-12-17 23:59:10+00:00,NaN,NaN,Unknown,NaN,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.596289,212,15.681124,69.141730
2166224,2828,2019-12-17 23:59:46+00:00,Norway,NaN,Passenger ships,< 1000 GT,0,0.000481,0.000004,0.001525,...,8.660000e-08,2.925000e-07,6.400000e-09,0.020949,0.155023,0.001,2.406429,362,12.016417,65.655110

In [ ]:
import track_builder as tb
path = r"C:\Users\lamin\OneDrive\Documents\Maitrise en info Canada\ASTD project\data\ASTD_area_level3_201902.csv"


# 2) load the first day only
df = tb.load_astd_data(path, sampling=[0])

df

Loading ASTD CSVs:   0%|          | 0/1 [00:00<?, ?it/s]

,shipid,date_time_utc,flagname,iceclass,astd_cat,sizegroup_gt,fuelquality,fuelcons,co,co2,...,blackcarbon,organiccarbon,oilbilgewater,blackwater,greywater,garbage,dist_nextpoint,sec_nextpoint,longitude,latitude
0,4742,2019-02-01 00:00:00+00:00,NaN,NaN,Unknown,NaN,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.660385,59,-24.104044,64.800125
1,85,2019-02-01 00:00:00+00:00,NaN,NaN,Unknown,NaN,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,367,23.036667,63.827835
2,402,2019-02-01 00:00:00+00:00,NaN,NaN,Unknown,NaN,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.761689,364,13.225843,68.087990
3,2693,2019-02-01 00:00:00+00:00,Norway,NaN,Fishing vessels,< 1000 GT,0,0.001065,0.000008,0.003378,...,1.918000e-07,6.479000e-07,6.400000e-09,0.000418,0.003092,0.000,164.255230,361,16.704500,69.670420
4,2840,2019-02-01 00:00:00+00:00,Norway,NaN,Fishing vessels,1000 - 4999 GT,0,0.009725,0.000072,0.030827,...,1.750400e-06,5.912500e-06,2.660000e-08,0.001253,0.009276,0.000,2.382778,361,7.730377,63.108290
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
619636,2600,2019-02-01 23:59:58+00:00,Iceland,NaN,Fishing vessels,< 1000 GT,0,0.000547,0.000004,0.001735,...,9.850000e-08,3.327000e-07,2.900000e-09,0.000522,0.001714,0.000,2.838267,161,-21.940878,64.150925
619637,1779,2019-02-01 23:59:58+00:00,Sweden,FS Ice Class 1B,Passenger ships,10000 - 24999,2,0.023465,0.000079,0.074841,...,4.223700e-06,4.994600e-06,1.060000e-08,0.175000,0.575000,0.005,0.668459,180,19.534966,60.226410
619638,949,2019-02-01 23:59:58+00:00,NaN,NaN,Unknown,NaN,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2.037249,400,17.145426,61.207092
619639,358,2019-02-01 23:59:58+00:00,NaN,NaN,Unknown,NaN,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2.446342,369,5.639360,62.339905
619640,844,2019-02-01 23:59:58+00:00,NaN,NaN,Unknown,NaN,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.887880,360,24.656990,70.994480

In [ ]:
# 3) load the first, the 4rd day and the 11th day
df = tb.load_astd_data(path, sampling=[0, 3, 10])

Loading ASTD CSVs:   0%|          | 0/1 [00:00<?, ?it/s]

In [3]:
df

,shipid,date_time_utc,flagname,iceclass,astd_cat,sizegroup_gt,fuelquality,fuelcons,co,co2,...,blackcarbon,organiccarbon,oilbilgewater,blackwater,greywater,garbage,dist_nextpoint,sec_nextpoint,longitude,latitude
0,403,2019-02-01 00:00:00+00:00,NaN,NaN,Unknown,NaN,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,370,13.714833,68.298164
1,85,2019-02-01 00:00:00+00:00,NaN,NaN,Unknown,NaN,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,367,23.036667,63.827835
2,402,2019-02-01 00:00:00+00:00,NaN,NaN,Unknown,NaN,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.761689,364,13.225843,68.087990
3,4742,2019-02-01 00:00:00+00:00,NaN,NaN,Unknown,NaN,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.660385,59,-24.104044,64.800125
4,2693,2019-02-01 00:00:00+00:00,Norway,NaN,Fishing vessels,< 1000 GT,0,0.001065,0.000008,0.003378,...,1.918000e-07,6.479000e-07,6.400000e-09,0.000418,0.003092,0.000,164.255230,361,16.704500,69.670420
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1801108,4509,2019-02-11 23:59:58+00:00,NaN,NaN,Fishing vessels,1000 - 4999 GT,0,0.002828,0.000021,0.008965,...,5.090000e-07,1.719400e-06,1.830000e-08,0.000861,0.006372,0.000,1.013650,248,-21.941510,64.153870
1801109,3081,2019-02-11 23:59:58+00:00,Norway,NaN,Passenger ships,1000 - 4999 GT,0,0.001568,0.000012,0.004972,...,2.823000e-07,9.536000e-07,1.600000e-08,0.052228,0.386487,0.004,4.306562,361,6.917785,62.780098
1801110,140,2019-02-11 23:59:58+00:00,NaN,NaN,Unknown,NaN,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2.784117,185,-18.526907,65.972080
1801111,687,2019-02-11 23:59:58+00:00,NaN,NaN,Unknown,NaN,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.848836,369,13.531215,68.071570
1801112,2706,2019-02-11 23:59:58+00:00,Netherlands,NaN,General cargo ships,1000 - 4999 GT,3,0.010217,0.000076,0.032387,...,1.839000e-06,6.211800e-06,3.980000e-08,0.001719,0.012719,0.000,2.028546,540,-22.038603,64.045135

In [18]:
# 9) quality_threshold_minutes: filtre qualité après sampling
df = tb.load_astd_data(path, sampling=[0, -1], quality_threshold_minutes=15)
df

Loading ASTD CSVs:   0%|          | 0/1 [00:00<?, ?it/s]

c:\Users\lamin\OneDrive\Documents\Maitrise en info Canada\ASTD project\TrackBuilder\track_builder\core\io_helpers.py:139: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  tmp["_month"] = tmp["date_time_utc"].dt.to_period("M").astype(str)

,shipid,date_time_utc,flagname,iceclass,astd_cat,sizegroup_gt,fuelquality,fuelcons,co,co2,...,blackcarbon,organiccarbon,oilbilgewater,blackwater,greywater,garbage,dist_nextpoint,sec_nextpoint,longitude,latitude
0,4742,2019-02-01 00:00:00+00:00,NaN,NaN,Unknown,NaN,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.660385,59,-24.104044,64.800125
1,11382,2019-02-01 00:00:01+00:00,Luxembourg,FS Ice Class 1A,General cargo ships,1000 - 4999 GT,1,0.004775,0.000035,0.015136,...,8.595000e-07,2.903100e-06,3.980000e-08,0.001719,0.012719,0.000,1.014266,540,24.519453,65.663030
2,12652,2019-02-01 00:00:02+00:00,Netherlands,FS Ice Class 1A,General cargo ships,1000 - 4999 GT,3,0.001709,0.000013,0.005418,...,3.076000e-07,1.039200e-06,2.360000e-08,0.001019,0.007537,0.000,2.094786,320,20.331244,63.687460
3,18368,2019-02-01 00:00:02+00:00,Netherlands,FS Ice Class 1A,General cargo ships,5000 - 9999 GT,1,0.013873,0.000073,0.043978,...,2.497200e-06,5.551900e-06,9.350000e-08,0.003056,0.022611,0.000,0.934383,528,23.711811,64.222946
4,3563,2019-02-01 00:00:02+00:00,Iceland,NaN,Fishing vessels,1000 - 4999 GT,0,0.001371,0.000010,0.004345,...,2.467000e-07,8.334000e-07,1.100000e-08,0.000517,0.003828,0.000,1.857814,149,-20.267567,63.444400
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
156096,6405,2019-02-28 23:59:54+00:00,Iceland,FS Ice Class 1C,Other activities,< 1000 GT,0,0.000509,0.000004,0.001614,...,9.160000e-08,3.096000e-07,4.100000e-09,0.000742,0.002438,0.000,2.219900,229,-21.934925,64.150800
156097,14814,2019-02-28 23:59:57+00:00,Cyprus,NaN,Bulk carriers,25000 - 49999,2,0.035347,0.000231,0.112199,...,6.362400e-06,1.845890e-05,9.560000e-08,0.004219,0.031219,0.000,2.921388,540,17.356630,68.436485
156098,435,2019-02-28 23:59:58+00:00,NaN,NaN,Unknown,NaN,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.334341,361,14.201718,68.151520
156099,9984,2019-02-28 23:59:58+00:00,Portugal (Mar),FS Ice Class 1A Super,Container ships,10000 - 24999,3,0.038278,0.000187,0.121804,...,6.890000e-06,1.388960e-05,6.380000e-08,0.002604,0.019271,0.000,8.538514,360,26.906500,60.423170
156100,9996,2019-02-28 23:59:58+00:00,Estonia,FS Ice Class 1A Super,Passenger ships,25000 - 49999,2,0.354617,0.002624,1.133517,...,6.383110e-05,2.156072e-04,1.780000e-08,0.130642,0.966754,0.013,2977.666300,301,20.222921,59.787865

In [ ]:

# 12) error case 
try:
    df = tb.load_astd_data(path, sampling=[31])  # interdit (doit être entre -31 et 30)
except ValueError as e:
    print("OK (caught):", e)

Loading ASTD CSVs:   0%|          | 0/1 [00:00<?, ?it/s]

OK (caught): Day indices must be between -31 and 30.

# ====== Testing the visualization function =======

In [2]:
import track_builder as tb

path = r"C:\Users\lamin\OneDrive\Documents\Maitrise en info Canada\ASTD project\data\ASTD_area_level3_201902.csv"
df = tb.load_astd_data(path, usecols="default", sampling=0.1, quality_threshold_minutes=30)

fig = tb.plot_ship_tracks(df, show_points=True, color_by="shipid")
fig.show()

Loading ASTD CSVs:   0%|          | 0/1 [00:00<?, ?it/s]

c:\Users\lamin\OneDrive\Documents\Maitrise en info Canada\ASTD project\TrackBuilder\track_builder\core\io_helpers.py:139: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  tmp["_month"] = tmp["date_time_utc"].dt.to_period("M").astype(str)

In [14]:
fig = tb.plot_ship_tracks(df, show_points=True, color_by="flagname")
fig.show()

In [ ]:
import track_builder as tb

tracks = tb.build_track_table(df)
# taking a track that exists:
track0 = tracks['track_id'].iloc[0]
print(track0)

tracks

# fig2 = tb.plot_individual_track(track0, tracks, df, show_segments=True)
# fig2.show()

Processing 16517 records
Data sample after cleaning:
  Date range: 2019-02-01 00:02:40+00:00 to 2019-02-28 23:57:08+00:00
  Ship types: ['unknown' 'fishing vessels' 'other activities' 'general cargo ships'
 'chemical tankers']
  Unique ships: 32
Creating segments for 32 unique shipids
Created 32 segments
Sample segment: unknown|nan|nan|nan
Found 32 segments across 1 time periods
Created 32 tracks
track_001

      month  segment_id   track_id
0   2019-02         157  track_001
1   2019-02        1421  track_002
2   2019-02        1707  track_003
3   2019-02         166  track_004
4   2019-02        3960  track_005
5   2019-02         208  track_006
6   2019-02        2931  track_007
7   2019-02         200  track_008
8   2019-02         179  track_009
9   2019-02         217  track_010
10  2019-02         267  track_011
11  2019-02         218  track_012
12  2019-02        4663  track_013
13  2019-02       18594  track_014
14  2019-02       18186  track_015
15  2019-02       19123  track_016
16  2019-02       19667  track_017
17  2019-02       20278  track_018
18  2019-02       21512  track_019
19  2019-02        7083  track_020
20  2019-02        7865  track_021
21  2019-02        9211  track_022
22  2019-02       11245  track_023
23  2019-02       11323  track_024
24  2019-02       12551  track_025
25  2019-02       13189  track_026
26  2019-02       16306  track_027
27  2019-02       17657  track_028
28  2019-02       13243  track_029
29  2019-02       17735  track_030
30  2019-02       17754  track_031
31  2019-02       17733  track_032

# =========== Verification =============

In [4]:
import pandas as pd
import track_builder as tb

# ================================================================
# 0) Parameters (adjust the path and year if needed)
# ================================================================
BASE_PATH = r"C:\Users\lamin\OneDrive\Documents\Maitrise en info Canada\ASTD project\data"
YEAR      = 2019
# At least 5 months (adjust as needed)
MONTHS_TO_LOAD = [5, 6, 7, 8, 9]

# Keep it lightweight: first and last day of each month + quality filter
USECOLS   = "default"
SAMPLING  = [0, -1]
QUAL_MIN  = 60


# ================================================================
# 1) Load the first and last days of at least 5 months
#    (respects the sampling setting sampling=[0, -1])
# ================================================================
df = tb.load_astd_monthly(
    BASE_PATH, YEAR, months=MONTHS_TO_LOAD, progress=True,
    usecols=USECOLS, sampling=SAMPLING, quality_threshold_minutes=QUAL_MIN
)
if df.empty:
    raise RuntimeError("Aucune donnée chargée. Vérifie chemin/année/mois.")
df["yyyymm"] = df["date_time_utc"].dt.strftime("%Y%m")

print("Mois couverts:", sorted(df["yyyymm"].unique().tolist()))
print(f"Total lignes (échantillon 1er/dernier jours/5+ mois): {len(df):,}")


# ================================================================
# 2) Build the track table (tracks) to associate segments
#    with tracks across months
#    -> based on the previous student's logic in main.py
# ================================================================
tracks = tb.build_track_table(df)

# Normalize a 'month_yyyymm' field for proper joining
if "month" in tracks.columns:
    # Generally 'YYYY-MM' -> 'YYYYMM'
    tracks = tracks.assign(month_yyyymm=tracks["month"].astype(str).str.replace("-", "", regex=False))
elif "date_time_utc" in tracks.columns:
    tracks = tracks.assign(month_yyyymm=pd.to_datetime(tracks["date_time_utc"], errors="coerce").dt.strftime("%Y%m"))
else:
    raise KeyError("La table tracks ne contient pas 'month' (ni date pour l’inférer).")

# Resolve identifier column names
pos_seg_col   = "shipid" if "shipid" in df.columns else ("segment_id" if "segment_id" in df.columns else None)  # côté positions
seg_col_track = "segment_id" if "segment_id" in tracks.columns else ("shipid" if "shipid" in tracks.columns else None)  # côté tracks
if pos_seg_col is None or seg_col_track is None:
    raise KeyError("Impossible de résoudre l’identifiant segment/navire (shipid/segment_id).")

print(f"Colonnes d’identifiants: positions={pos_seg_col}  tracks={seg_col_track}")


# ================================================================
# 3) Choose a track identifier (track_id) and find
#    all shipids (segments) for each month
#    -> select the track with the best coverage across months
# ================================================================
coverage = (
    tracks.groupby("track_id")["month_yyyymm"]
          .nunique()
          .sort_values(ascending=False)
)
if coverage.empty:
    raise ValueError("Aucun track_id trouvé dans la table de suivi.")

chosen_track = coverage.index[0]
covered_n    = int(coverage.iloc[0])
print(f"Track choisi: {chosen_track} (couvre {covered_n} mois)")

# shipid/segment_id per month for this track
per_month_shipids = (
    tracks.loc[tracks["track_id"] == chosen_track, ["month_yyyymm", seg_col_track]]
          .dropna()
          .groupby("month_yyyymm")[seg_col_track]
          .apply(lambda s: sorted(set(s.tolist())))
          .sort_index()
          .to_dict()
)
print("Ship IDs par mois (aperçu):")
for m, ids in per_month_shipids.items():
    print(f"  {m}: {len(ids)} id(s) → {ids[:5]}{'...' if len(ids)>5 else ''}")


# ================================================================
# 4) Load ship IDs for each month
#    (reload each month then filter by the shipids belonging to this track)
#    -> aligns with the approach used in the example
# ================================================================
def load_month_subset(year: int, month: int) -> pd.DataFrame:
    """Recharge le mois COMPLET (sans sampling) pour garantir des points présents pour le shipid."""
    return tb.load_astd_monthly(
        BASE_PATH, year, months=[month], progress=False,
        usecols=USECOLS, sampling=None,  # <<< IMPORTANT: sampling désactivé ici
        # quality_threshold_minutes=30  # tu peux activer si tu veux lisser
    )

positions_list = []
target_months  = sorted(set(tracks.loc[tracks["track_id"] == chosen_track, "month_yyyymm"]))

for m_str in target_months:
    y, mm = int(m_str[:4]), int(m_str[4:])
    dfi   = load_month_subset(y, mm)  # mois complet
    shipids = set(per_month_shipids.get(m_str, []))
    if not shipids:
        continue
    dfi = dfi[dfi[pos_seg_col].isin(shipids)].copy()
    positions_list.append(dfi)

positions_for_track = pd.concat(positions_list, ignore_index=True)
print(f"Positions retenues pour le track {chosen_track}: {len(positions_for_track):,} lignes")


# ================================================================
# 5) Plot the chosen track with its segments

# ================================================================
# a) Detailed view (follows the logic of the previous student)
fig_track = tb.plot_individual_track(
    chosen_track,
    tracks,
    positions_for_track,
    show_segments=True,                 # one polyline per segment (often = shipid)
    map_style="open-street-map",
    title=f"Track {chosen_track} – vue détaillée",
)
display(fig_track)

Loading ASTD CSVs:   0%|          | 0/5 [00:00<?, ?it/s]

c:\Users\lamin\OneDrive\Documents\Maitrise en info Canada\ASTD project\TrackBuilder\track_builder\core\io_helpers.py:139: UserWarning:

Converting to PeriodArray/Index representation will drop timezone information.

Mois couverts: ['201905', '201906', '201907', '201908', '201909']
Total lignes (échantillon 1er/dernier jours/5+ mois): 2,335,451
Processing 2335451 records
Data sample after cleaning:
  Date range: 2019-05-01 00:00:00+00:00 to 2019-09-30 23:59:58+00:00
  Ship types: ['unknown' 'fishing vessels' 'bulk carriers' 'general cargo ships'
 'other activities' 'chemical tankers' 'crude oil tankers'
 'passenger ships' 'ro-ro cargo ships' 'other service offshore vessels'
 'offshore supply ships' 'oil product tankers' 'gas tankers'
 'container ships' 'refrigerated cargo ships' 'cruise ships' 'nan']
  Unique ships: 8081
Creating segments for 8081 unique shipids
Created 8081 segments
Sample segment: unknown|nan|nan|nan
Found 8081 segments across 5 time periods
Created 6744 tracks
Colonnes d’identifiants: positions=shipid  tracks=segment_id
Track choisi: track_231 (couvre 5 mois)
Ship IDs par mois (aperçu):
  201905: 1 id(s) → [5756]
  201906: 1 id(s) → [278]
  201907: 1 id(s) → [455]
  201908: 1 id(s) → [674]
  201909: 1 id(s) → [795]
Positions retenues pour le track track_231: 62,911 lignes

In [5]:
# combien de points par shipid après filtrage ?
counts = (positions_for_track
          .groupby(pos_seg_col).size()
          .sort_values())
print("Points par shipid:", counts.head(10), " ...max:", counts.max())

# combien de points par (mois, shipid) ?
positions_for_track["yyyymm"] = positions_for_track["date_time_utc"].dt.strftime("%Y%m")
counts_m = (positions_for_track
            .groupby(["yyyymm", pos_seg_col]).size()
            .sort_values())
print("Points par (mois, shipid):")
print(counts_m.head(15))

Points par shipid: shipid
795     11012
5756    11373
278     13386
674     13478
455     13662
dtype: int64  ...max: 13662
Points par (mois, shipid):
yyyymm  shipid
201909  795       11012
201905  5756      11373
201906  278       13386
201908  674       13478
201907  455       13662
dtype: int64

In [6]:
# 0) S'assurer de la colonne yyyymm
if "yyyymm" not in positions_for_track.columns:
    positions_for_track["yyyymm"] = positions_for_track["date_time_utc"].dt.strftime("%Y%m")

# 1) Construire la vérité terrain : shipids réellement présents dans positions_for_track
present_ids_by_month = {
    m: sorted(sub[pos_seg_col].dropna().unique().tolist())
    for m, sub in positions_for_track.groupby("yyyymm")
}
print("ShipIDs réellement présents par mois :", present_ids_by_month)

# 2) Helper pour tracer UN (mois, shipid)
def plot_one_segment_month(track_id, month_yyyymm, shipid_value):
    # mini track_table filtrée (si vide, on passe la table complète en fallback)
    if "month_yyyymm" not in tracks.columns and "month" in tracks.columns:
        tracks["month_yyyymm"] = tracks["month"].astype(str).replace("-", "", regex=True)

    tt = tracks[
        (tracks["track_id"] == track_id) &
        (tracks["month_yyyymm"] == month_yyyymm) &
        (tracks[seg_col_track] == shipid_value)
    ].copy()

    sub = positions_for_track[
        (positions_for_track["yyyymm"] == month_yyyymm) &
        (positions_for_track[pos_seg_col] == shipid_value)
    ].copy()

    if len(sub) < 2:
        print(f"[INFO] {month_yyyymm} | shipid={shipid_value}: {len(sub)} point(s) → pas de ligne.")
        # Si tu veux voir même 1 point, décommente la ligne suivante:
        # return tb.plot_ship_tracks(sub, show_points=True, title=f"{track_id} — {month_yyyymm} — {shipid_value}")
        return None

    return tb.plot_individual_track(
        track_id=track_id,
        track_table=(tt if not tt.empty else tracks),  # fallback robuste
        astd_data=sub,
        show_segments=True,
        map_style="open-street-map",
        title=f"Track {track_id} — {month_yyyymm} — shipid {shipid_value}",
    )

# 3) Boucler sur les (mois, shipid) RÉELS et tracer
for m in sorted(present_ids_by_month.keys()):
    for sid in present_ids_by_month[m]:
        fig = plot_one_segment_month(chosen_track, m, sid)
        if fig is not None:
            fig.show()

ShipIDs réellement présents par mois : {'201905': [5756], '201906': [278], '201907': [455], '201908': [674], '201909': [795]}

In [7]:

present_ids_by_month = {
    m: sorted(sub[pos_seg_col].dropna().unique().tolist())
    for m, sub in positions_for_track.groupby("yyyymm")
}
print("ShipIDs réellement présents par mois :", present_ids_by_month)

# pour chaque mois afficher une ligne de df par shipid
for m in sorted(present_ids_by_month.keys()):
    shipids = present_ids_by_month[m]
    for sid in shipids:
        df = positions_for_track[
            (positions_for_track["yyyymm"] == m) &
            (positions_for_track[pos_seg_col] == sid)
        ].copy()

        # afficher avec head()
        display(df.head(1))

ShipIDs réellement présents par mois : {'201905': [5756], '201906': [278], '201907': [455], '201908': [674], '201909': [795]}

,shipid,date_time_utc,flagname,iceclass,astd_cat,sizegroup_gt,dist_nextpoint,sec_nextpoint,longitude,latitude,yyyymm
0,5756,2019-05-01 00:01:38+00:00,NaN,NaN,Fishing vessels,< 1000 GT,2.123252,252,-17.346937,66.045647,201905

,shipid,date_time_utc,flagname,iceclass,astd_cat,sizegroup_gt,dist_nextpoint,sec_nextpoint,longitude,latitude,yyyymm
11373,278,2019-06-01 00:04:47+00:00,NaN,NaN,Fishing vessels,< 1000 GT,1.320521,130,-17.346912,66.04567,201906

,shipid,date_time_utc,flagname,iceclass,astd_cat,sizegroup_gt,dist_nextpoint,sec_nextpoint,longitude,latitude,yyyymm
24759,455,2019-07-01 00:03:49+00:00,NaN,NaN,Fishing vessels,< 1000 GT,0.768411,119,-17.346947,66.04567,201907

,shipid,date_time_utc,flagname,iceclass,astd_cat,sizegroup_gt,dist_nextpoint,sec_nextpoint,longitude,latitude,yyyymm
38421,674,2019-08-01 00:02:20+00:00,NaN,NaN,Fishing vessels,< 1000 GT,3.101632,29,-17.34696,66.045601,201908

,shipid,date_time_utc,flagname,iceclass,astd_cat,sizegroup_gt,dist_nextpoint,sec_nextpoint,longitude,latitude,yyyymm
51899,795,2019-09-01 00:02:54+00:00,NaN,NaN,Fishing vessels,< 1000 GT,1.355183,21,-17.346939,66.045654,201909

In [40]:
df_month_3 = df[df['date_time_utc'].dt.month == 3]
df_month_3 = df_month_3[df_month_3['shipid'] == 3332]
print("Affichage du premier point du mois 3 pour le shipid 3332:")
display(df_month_3.head(1))

Affichage du premier point du mois 3 pour le shipid 3332:

,shipid,date_time_utc,flagname,iceclass,astd_cat,sizegroup_gt,dist_nextpoint,sec_nextpoint,longitude,latitude,yyyymm
158996,3332,2019-03-01 00:03:26+00:00,Antigua & Barbuda,FS Ice Class 1A,General cargo ships,5000 - 9999 GT,938.564697,170,18.876686,60.794178,201903

# ======== verif 2 ========

In [11]:
# ===== 3’) Sélectionner un track couvrant EXACTEMENT les mois ET avec >=2 points par mois =====

target_set = {f"{YEAR}{m:02d}" for m in MONTHS_TO_LOAD}

# ensemble des mois par track_id (sur l’aperçu)
months_by_track = (tracks.groupby("track_id")["month_yyyymm"]
                   .agg(lambda s: set(s.dropna().astype(str).tolist())))

# candidats: ensemble == target_set
exact_tracks = months_by_track[months_by_track.apply(lambda s: s == target_set)]
if exact_tracks.empty:
    raise ValueError(f"Aucun track ne couvre EXACTEMENT {sorted(target_set)} (avec sampling={SAMPLING}).")

# ---- Charger chaque mois COMPLET une seule fois (cache), sans filtre qualité agressif ----
def load_month_full(year: int, month: int) -> pd.DataFrame:
    return tb.load_astd_monthly(
        BASE_PATH, year, months=[month], progress=False,
        usecols=USECOLS, sampling=None, quality_threshold_minutes=0
    )

month_cache = {}
for m_str in sorted(target_set):
    y, mm = int(m_str[:4]), int(m_str[4:])
    dfi = load_month_full(y, mm)
    if dfi.empty:
        month_cache[m_str] = pd.DataFrame(columns=df.columns)
    else:
        # on standardise le nom d’id côté positions
        if "shipid" in dfi.columns:
            dfi["_segpos"] = dfi["shipid"]
        elif "segment_id" in dfi.columns:
            dfi["_segpos"] = dfi["segment_id"]
        else:
            raise KeyError("Ni 'shipid' ni 'segment_id' dans les données rechargées.")
        month_cache[m_str] = dfi[["_segpos", "latitude", "longitude", "date_time_utc"]].copy()

# ---- Évaluer chaque candidat : faut >=2 points pour AU MOINS un shipid par mois ----
best_tid, best_total_pts = None, -1
best_per_month_ids = None

for tid in exact_tracks.index:
    # shipids annoncés par tracks pour chaque mois cible
    per_m_ids = (
        tracks.loc[(tracks["track_id"] == tid) & (tracks["month_yyyymm"].isin(target_set)), ["month_yyyymm", seg_col_track]]
              .dropna()
              .groupby("month_yyyymm")[seg_col_track]
              .apply(lambda s: sorted(set(s.tolist())))
              .to_dict()
    )

    ok = True
    total_pts = 0
    chosen_ids_per_month = {}

    for m_str in target_set:
        ids = per_m_ids.get(m_str, [])
        if not ids:
            ok = False; break

        dfi = month_cache[m_str]
        # nombre de points par shipid de ce mois
        counts = dfi["_segpos"].value_counts()

        # garder les shipid avec >=2 points
        good_ids = [sid for sid in ids if counts.get(sid, 0) >= 2]
        if not good_ids:
            ok = False; break

        # on peut en garder plusieurs ; on comptabilise
        month_pts = sum(int(counts.get(sid, 0)) for sid in good_ids)
        total_pts += month_pts
        chosen_ids_per_month[m_str] = good_ids

    if ok and total_pts > best_total_pts:
        best_tid, best_total_pts = tid, total_pts
        best_per_month_ids = chosen_ids_per_month

if best_tid is None:
    raise ValueError(
        "Parmi les tracks exacts, aucun n’a >=2 points pour chaque mois après rechargement complet. "
        "Relaxe la contrainte (par ex. QUAL_MIN=0, sampling=None pour la construction des tracks) "
        "ou essaie d’autres mois."
    )

chosen_track = best_tid
print(f"Track choisi (exact mois + >=2 pts/mois): {chosen_track} ({best_total_pts} points total)")

# ===== 4’) Construire positions_for_track à partir des shipid retenus (>=2 pts/mois) =====
positions_list = []
for m_str, ids in best_per_month_ids.items():
    y, mm = int(m_str[:4]), int(m_str[4:])
    dfi = month_cache[m_str]
    dfi = dfi[dfi["_segpos"].isin(set(ids))].copy()
    # remettre le bon nom de colonne pour la suite (plot)
    dfi[pos_seg_col] = dfi["_segpos"]
    positions_list.append(dfi)

positions_for_track = pd.concat(positions_list, ignore_index=True)
print(f"Positions retenues (>=2 pts/mois): {len(positions_for_track):,} lignes")

# ===== 5) Tracé identique =====
fig = tb.plot_individual_track(
    chosen_track, tracks, positions_for_track,
    show_segments=True,
    map_style="open-street-map",
    title=f"Track {chosen_track} – EXACT {sorted(target_set)} (>=2 pts/mois)",
)
fig.show()

ValueError: Aucun track ne couvre EXACTEMENT ['201905', '201906', '201907', '201908', '201909'] (avec sampling=[0, -1]).