In [4]:
import pandas as pd
path = r"C:\Users\lamin\OneDrive\Documents\Maitrise en info Canada\ASTD project\data\ASTD_area_level3_201902.csv"

df = pd.read_csv(path, sep=";", low_memory=False)

df.head(10)

:

:

In [1]:
import track_builder as tb

files = [r"C:\Users\lamin\OneDrive\Documents\Maitrise en info Canada\ASTD project\data\ASTD_area_level3_201901.csv",
         r"C:\Users\lamin\OneDrive\Documents\Maitrise en info Canada\ASTD project\data\ASTD_area_level3_201902.csv"]

df = tb.load_astd_data(files[0])

df.head(5)

Loading ASTD CSVs: 100%|██████████| 1/1 [01:53<00:00, 113.53s/it]
c:\Users\lamin\OneDrive\Documents\Maitrise en info Canada\ASTD project\TrackBuilder\track_builder\core\io_helpers.py:143: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  df["month"] = df["date_time_utc"].dt.to_period("M").astype(str)

,shipid,date_time_utc,flagname,iceclass,astd_cat,sizegroup_gt,fuelquality,fuelcons,co,co2,...,organiccarbon,oilbilgewater,blackwater,greywater,garbage,dist_nextpoint,sec_nextpoint,longitude,latitude,month
0,162,2019-01-01 00:00:00+00:00,iceland,<NA>,unknown,<NA>,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2.242847,209,-21.827280,64.134210,2019-01
1,385,2019-01-01 00:00:00+00:00,<NA>,<NA>,unknown,<NA>,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2.987542,370,14.245747,67.389120,2019-01
2,3619,2019-01-01 00:00:00+00:00,norway,<NA>,other activities,1000 - 4999 gt,4,0.016730,0.000124,0.053035,...,1.017200e-05,2.720000e-08,0.001281,0.009481,0.0,491.440920,369,14.545295,68.205574,2019-01
3,1645,2019-01-01 00:00:00+00:00,iceland,<NA>,fishing vessels,< 1000 gt,0,0.001227,0.000009,0.003890,...,7.460000e-07,6.400000e-09,0.001170,0.003844,0.0,0.731465,361,-23.703033,64.896220,2019-01
4,2490,2019-01-01 00:00:00+00:00,iceland,<NA>,fishing vessels,1000 - 4999 gt,0,0.000935,0.000007,0.002964,...,5.685000e-07,6.100000e-09,0.000797,0.002619,0.0,2.241636,82,-23.127956,66.069336,2019-01

In [4]:
df

,shipid,date_time_utc,flagname,iceclass,astd_cat,sizegroup_gt,fuelquality,fuelcons,co,co2,...,organiccarbon,oilbilgewater,blackwater,greywater,garbage,dist_nextpoint,sec_nextpoint,longitude,latitude,month
0,162,2019-01-01 00:00:00+00:00,iceland,<NA>,unknown,<NA>,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2.242847,209,-21.827280,64.134210,2019-01
1,385,2019-01-01 00:00:00+00:00,<NA>,<NA>,unknown,<NA>,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2.987542,370,14.245747,67.389120,2019-01
2,3619,2019-01-01 00:00:00+00:00,norway,<NA>,other activities,1000 - 4999 gt,4,0.016730,0.000124,0.053035,...,1.017200e-05,2.720000e-08,0.001281,0.009481,0.0,491.440920,369,14.545295,68.205574,2019-01
3,1645,2019-01-01 00:00:00+00:00,iceland,<NA>,fishing vessels,< 1000 gt,0,0.001227,0.000009,0.003890,...,7.460000e-07,6.400000e-09,0.001170,0.003844,0.0,0.731465,361,-23.703033,64.896220,2019-01
4,2490,2019-01-01 00:00:00+00:00,iceland,<NA>,fishing vessels,1000 - 4999 gt,0,0.000935,0.000007,0.002964,...,5.685000e-07,6.100000e-09,0.000797,0.002619,0.0,2.241636,82,-23.127956,66.069336,2019-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18219900,250,2019-01-31 23:59:57+00:00,<NA>,<NA>,unknown,<NA>,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.916833,249,-20.317630,65.825250,2019-01
18219901,145,2019-01-31 23:59:58+00:00,<NA>,<NA>,unknown,<NA>,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1.117709,202,-14.007736,64.786480,2019-01
18219902,931,2019-01-31 23:59:58+00:00,<NA>,<NA>,unknown,<NA>,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,3.387100,180,17.170370,60.678890,2019-01
18219903,2117,2019-01-31 23:59:58+00:00,iceland,<NA>,other activities,< 1000 gt,0,0.000807,0.000006,0.002558,...,4.907000e-07,6.400000e-09,0.001176,0.003865,0.0,1.346573,363,-23.598950,65.684410,2019-01
18219904,882,2019-01-31 23:59:58+00:00,<NA>,<NA>,unknown,<NA>,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2.373756,370,11.307200,64.912735,2019-01

In [1]:
import track_builder as tb

files = [r"C:\Users\lamin\OneDrive\Documents\Maitrise en info Canada\ASTD project\data\ASTD_area_level3_201901.csv",
         r"C:\Users\lamin\OneDrive\Documents\Maitrise en info Canada\ASTD project\data\ASTD_area_level3_201902.csv"]

df_with_optimized_config = tb.load_astd_data(files[0], use_optimized_config=True)

Loading ASTD CSVs: 100%|██████████| 1/1 [01:30<00:00, 90.88s/it]
c:\Users\lamin\OneDrive\Documents\Maitrise en info Canada\ASTD project\TrackBuilder\track_builder\core\io_helpers.py:143: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  df["month"] = df["date_time_utc"].dt.to_period("M").astype(str)

In [2]:
df_with_optimized_config

,shipid,date_time_utc,flagname,iceclass,astd_cat,sizegroup_gt,dist_nextpoint,sec_nextpoint,longitude,latitude,month
0,162,2019-01-01 00:00:00+00:00,iceland,<NA>,unknown,<NA>,2.242847,209,-21.827280,64.134209,2019-01
1,385,2019-01-01 00:00:00+00:00,<NA>,<NA>,unknown,<NA>,2.987542,370,14.245747,67.389122,2019-01
2,3619,2019-01-01 00:00:00+00:00,norway,<NA>,other activities,1000 - 4999 gt,491.440918,369,14.545295,68.205574,2019-01
3,1645,2019-01-01 00:00:00+00:00,iceland,<NA>,fishing vessels,< 1000 gt,0.731465,361,-23.703033,64.896217,2019-01
4,2490,2019-01-01 00:00:00+00:00,iceland,<NA>,fishing vessels,1000 - 4999 gt,2.241636,82,-23.127956,66.069336,2019-01
...,...,...,...,...,...,...,...,...,...,...,...
18219900,250,2019-01-31 23:59:57+00:00,<NA>,<NA>,unknown,<NA>,0.916833,249,-20.317631,65.825249,2019-01
18219901,145,2019-01-31 23:59:58+00:00,<NA>,<NA>,unknown,<NA>,1.117709,202,-14.007736,64.786484,2019-01
18219902,931,2019-01-31 23:59:58+00:00,<NA>,<NA>,unknown,<NA>,3.387100,180,17.170370,60.678890,2019-01
18219903,2117,2019-01-31 23:59:58+00:00,iceland,<NA>,other activities,< 1000 gt,1.346573,363,-23.598949,65.684410,2019-01
18219904,882,2019-01-31 23:59:58+00:00,<NA>,<NA>,unknown,<NA>,2.373756,370,11.307200,64.912735,2019-01

In [ ]:
import pandas as pd
import os
from pathlib import Path

# 1. Définir les chemins
source_directory = Path(r"C:\Users\lamin\OneDrive\Documents\Maitrise en info Canada\ASTD project\data")
sample_directory = Path(r"C:\Users\lamin\OneDrive\Documents\Maitrise en info Canada\ASTD project\data_sample")

# # 2. Créer le dossier de destination s'il n'existe pas
# sample_directory.mkdir(exist_ok=True)

# print(f"Création des échantillons dans : {sample_directory}")

# # 3. Boucler sur les fichiers CSV, prendre les 100 premières lignes et sauvegarder
# for file_name in os.listdir(source_directory):
#     if file_name.endswith('.csv'):
#         source_file_path = source_directory / file_name
#         sample_file_path = sample_directory / file_name
        
#         print(f"  -> Traitement de {file_name}...")
        
#         # Lire seulement les 100 premières lignes du gros fichier
#         df_sample = pd.read_csv(source_file_path, sep=';', nrows=100)
        
#         # Sauvegarder ce petit DataFrame dans le nouveau dossier
#         # index=False est important pour ne pas ajouter une colonne d'index inutile
#         df_sample.to_csv(sample_file_path, sep=';', index=False)

# print("Terminé ! Votre dossier de test est prêt.")

Création des échantillons dans : C:\Users\lamin\OneDrive\Documents\Maitrise en info Canada\ASTD project\data_sample
  -> Traitement de ASTD_area_level3_201901.csv...
  -> Traitement de ASTD_area_level3_201902.csv...
  -> Traitement de ASTD_area_level3_201903.csv...
  -> Traitement de ASTD_area_level3_201904.csv...
  -> Traitement de ASTD_area_level3_201905.csv...
  -> Traitement de ASTD_area_level3_201906.csv...
  -> Traitement de ASTD_area_level3_201907.csv...
  -> Traitement de ASTD_area_level3_201908.csv...
  -> Traitement de ASTD_area_level3_201909.csv...
  -> Traitement de ASTD_area_level3_201910.csv...
  -> Traitement de ASTD_area_level3_201911.csv...
  -> Traitement de ASTD_area_level3_201912.csv...
Terminé ! Votre dossier de test est prêt.

In [1]:
import track_builder as tb

# Utilise le chemin vers tes données d'échantillon
sample_data_path = r"C:\Users\lamin\OneDrive\Documents\Maitrise en info Canada\ASTD project\data_sample"

# Teste load_astd_data sur le dossier complet d'échantillons
print("Test du chargement de tout le dossier d'échantillons...")
df_all_samples = tb.load_astd_data(sample_data_path)
print(df_all_samples.info())

Test du chargement de tout le dossier d'échantillons...

Loading ASTD CSVs: 100%|██████████| 12/12 [00:00<00:00, 69.68it/s]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   shipid          1200 non-null   int32
 1   date_time_utc   1200 non-null   datetime64[ns, UTC]
 2   flagname        299 non-null    string
 3   iceclass        0 non-null      string
 4   astd_cat        1200 non-null   string
 5   sizegroup_gt    299 non-null    string
 6   dist_nextpoint  1050 non-null   float32
 7   sec_nextpoint   1200 non-null   int32
 8   longitude       1200 non-null   float32
 9   latitude        1200 non-null   float32
 10  month           1200 non-null   object
dtypes: datetime64[ns, UTC](1), float32(3), int32(2), object(1), string(4)
memory usage: 79.8+ KB
None

c:\Users\lamin\OneDrive\Documents\Maitrise en info Canada\ASTD project\TrackBuilder\track_builder\core\io_helpers.py:142: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  df["month"] = df["date_time_utc"].dt.to_period("M").astype(str)

In [2]:
# Teste load_astd_monthly sur les échantillons
print("\nTest du chargement des mois de juillet à septembre...")
df_monthly_samples = tb.load_astd_monthly(sample_data_path, year=2019, months=[7, 8, 9])
print(df_monthly_samples.info())

Test du chargement des mois de juillet à septembre...

Loading ASTD CSVs: 100%|██████████| 3/3 [00:00<00:00, 265.67it/s]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   shipid          300 non-null    int32
 1   date_time_utc   300 non-null    datetime64[ns, UTC]
 2   flagname        199 non-null    string
 3   iceclass        0 non-null      string
 4   astd_cat        300 non-null    string
 5   sizegroup_gt    199 non-null    string
 6   dist_nextpoint  199 non-null    float32
 7   sec_nextpoint   300 non-null    int32
 8   longitude       300 non-null    float32
 9   latitude        300 non-null    float32
 10  month           300 non-null    object
dtypes: datetime64[ns, UTC](1), float32(3), int32(2), object(1), string(4)
memory usage: 20.1+ KB
None

c:\Users\lamin\OneDrive\Documents\Maitrise en info Canada\ASTD project\TrackBuilder\track_builder\io\astd_loader.py:67: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  out = pd.concat(frames, ignore_index=True)
c:\Users\lamin\OneDrive\Documents\Maitrise en info Canada\ASTD project\TrackBuilder\track_builder\core\io_helpers.py:142: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  df["month"] = df["date_time_utc"].dt.to_period("M").astype(str)

In [3]:
# --- Setup ---
# Define the path to a single sample file.
single_file = sample_data_path + "/ASTD_area_level3_201909.csv"
print(f"--- Loading a single file: {single_file} ---\n")

# --- Action ---
# Call the function with the single file path.
df_single = tb.load_astd_data(single_file)

# --- Verification ---
# Display the info and the first 5 rows of the resulting DataFrame.
df_single.info()
display(df_single.head())

--- Loading a single file: C:\Users\lamin\OneDrive\Documents\Maitrise en info Canada\ASTD project\data_sample/ASTD_area_level3_201909.csv ---

Loading ASTD CSVs: 100%|██████████| 1/1 [00:00<00:00, 250.02it/s]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   shipid          100 non-null    int32
 1   date_time_utc   100 non-null    datetime64[ns, UTC]
 2   flagname        100 non-null    string
 3   iceclass        0 non-null      string
 4   astd_cat        100 non-null    string
 5   sizegroup_gt    100 non-null    string
 6   dist_nextpoint  100 non-null    float32
 7   sec_nextpoint   100 non-null    int32
 8   longitude       100 non-null    float32
 9   latitude        100 non-null    float32
 10  month           100 non-null    object
dtypes: datetime64[ns, UTC](1), float32(3), int32(2), object(1), string(4)
memory usage: 6.8+ KB

c:\Users\lamin\OneDrive\Documents\Maitrise en info Canada\ASTD project\TrackBuilder\track_builder\core\io_helpers.py:142: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  df["month"] = df["date_time_utc"].dt.to_period("M").astype(str)

,shipid,date_time_utc,flagname,iceclass,astd_cat,sizegroup_gt,dist_nextpoint,sec_nextpoint,longitude,latitude,month
0,1,2019-09-11 00:03:58+00:00,norway,<NA>,fishing vessels,< 1000 gt,2.963552,369,25.965061,70.983147,2019-09
1,1,2019-09-11 00:16:17+00:00,norway,<NA>,fishing vessels,< 1000 gt,3.161857,361,25.964964,70.983162,2019-09
2,1,2019-09-11 01:04:49+00:00,norway,<NA>,fishing vessels,< 1000 gt,1.615317,368,25.965057,70.983116,2019-09
3,0,2019-09-11 01:12:55+00:00,norway,<NA>,passenger ships,1000 - 4999 gt,0.000000,370,12.286775,65.969124,2019-09
4,0,2019-09-11 01:25:15+00:00,norway,<NA>,passenger ships,1000 - 4999 gt,0.075766,370,12.286774,65.969124,2019-09

In [4]:
import pandas as pd

df_test = pd.read_csv(single_file, sep=";", low_memory=False)

df_test

,shipid,date_time_utc,flagname,iceclass,astd_cat,sizegroup_gt,fuelquality,fuelcons,co,co2,...,blackcarbon,organiccarbon,oilbilgewater,blackwater,greywater,garbage,dist_nextpoint,sec_nextpoint,longitude,latitude
0,0,2019-09-11 12:49:15,Norway,NaN,Passenger ships,1000 - 4999 GT,0,0.017209,1.273496e-04,0.054554,...,3.097700e-06,1.046340e-05,1.610000e-08,0.052517,0.388628,0.004,2236.542500,363,12.231715,65.924960
1,0,2019-09-11 06:18:44,Norway,NaN,Passenger ships,1000 - 4999 GT,0,0.009873,7.306260e-05,0.031298,...,1.777200e-06,6.003000e-06,1.700000e-08,0.055411,0.410040,0.004,1780.179600,383,12.316360,65.958664
2,0,2019-09-11 03:34:03,Norway,NaN,Passenger ships,1000 - 4999 GT,0,0.003432,2.539610e-05,0.010879,...,6.177000e-07,2.086600e-06,1.600000e-08,0.052228,0.386487,0.004,0.000000,361,12.286767,65.969124
3,0,2019-09-11 01:12:55,Norway,NaN,Passenger ships,1000 - 4999 GT,0,0.003517,2.602930e-05,0.011150,...,6.331000e-07,2.138600e-06,1.640000e-08,0.053530,0.396123,0.004,0.000000,370,12.286775,65.969124
4,0,2019-09-11 21:53:14,Norway,NaN,Passenger ships,1000 - 4999 GT,0,0.003527,2.609960e-05,0.011181,...,6.349000e-07,2.144400e-06,1.640000e-08,0.053675,0.397193,0.004,0.758668,371,12.286775,65.969120
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1,2019-09-11 03:13:07,Norway,NaN,Fishing vessels,< 1000 GT,0,0.001227,9.079800e-06,0.003890,...,2.209000e-07,7.460000e-07,6.400000e-09,0.000418,0.003092,0.000,1.884127,361,25.965015,70.983120
96,1,2019-09-11 18:14:18,Norway,NaN,Fishing vessels,< 1000 GT,0,0.001224,9.054600e-06,0.003879,...,2.202000e-07,7.439000e-07,6.400000e-09,0.000417,0.003083,0.000,253.087770,360,25.087502,71.188860
97,1,2019-09-11 13:58:45,Norway,NaN,Fishing vessels,< 1000 GT,0,0.001234,9.130100e-06,0.003911,...,2.221000e-07,7.501000e-07,6.400000e-09,0.000420,0.003109,0.000,447.042480,363,24.843563,71.177140
98,1,2019-09-11 03:43:26,Norway,NaN,Fishing vessels,< 1000 GT,0,0.000112,8.300000e-07,0.000356,...,2.020000e-08,6.820000e-08,6.000000e-10,0.000038,0.000283,0.000,1.314351,33,25.965070,70.983110
99,1,2019-09-11 10:37:28,Norway,NaN,Fishing vessels,< 1000 GT,0,0.001261,9.331300e-06,0.003997,...,2.270000e-07,7.667000e-07,6.600000e-09,0.000429,0.003178,0.000,1807.547600,371,25.725185,70.936356

In [5]:
# --- Setup ---
print(f"--- Loading all files from directory: {sample_data_path} ---\n")

# --- Action ---
# Call the function with the directory path.
df_directory = tb.load_astd_data(sample_data_path)

# --- Verification ---
# The resulting DataFrame should contain 1200 rows (12 files * 100 rows).
df_directory.info()

--- Loading all files from directory: C:\Users\lamin\OneDrive\Documents\Maitrise en info Canada\ASTD project\data_sample ---

Loading ASTD CSVs: 100%|██████████| 12/12 [00:00<00:00, 262.04it/s]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   shipid          1200 non-null   int32
 1   date_time_utc   1200 non-null   datetime64[ns, UTC]
 2   flagname        299 non-null    string
 3   iceclass        0 non-null      string
 4   astd_cat        1200 non-null   string
 5   sizegroup_gt    299 non-null    string
 6   dist_nextpoint  1050 non-null   float32
 7   sec_nextpoint   1200 non-null   int32
 8   longitude       1200 non-null   float32
 9   latitude        1200 non-null   float32
 10  month           1200 non-null   object
dtypes: datetime64[ns, UTC](1), float32(3), int32(2), object(1), string(4)
memory usage: 79.8+ KB

c:\Users\lamin\OneDrive\Documents\Maitrise en info Canada\ASTD project\TrackBuilder\track_builder\core\io_helpers.py:142: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  df["month"] = df["date_time_utc"].dt.to_period("M").astype(str)

In [6]:
# --- Setup ---
months_to_load = [1, 6, 12] # January, June, December
year_to_load = 2019
print(f"--- Loading months {months_to_load} for year {year_to_load} ---\n")

# --- Action ---
df_specific_months = tb.load_astd_monthly(sample_data_path, year=year_to_load, months=months_to_load)

# --- Verification ---
# The resulting DataFrame should contain 300 rows (3 files * 100 rows).
df_specific_months.info()

--- Loading months [1, 6, 12] for year 2019 ---

Loading ASTD CSVs: 100%|██████████| 3/3 [00:00<00:00, 277.63it/s]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   shipid          300 non-null    int32
 1   date_time_utc   300 non-null    datetime64[ns, UTC]
 2   flagname        0 non-null      string
 3   iceclass        0 non-null      string
 4   astd_cat        300 non-null    string
 5   sizegroup_gt    0 non-null      string
 6   dist_nextpoint  295 non-null    float32
 7   sec_nextpoint   300 non-null    int32
 8   longitude       300 non-null    float32
 9   latitude        300 non-null    float32
 10  month           300 non-null    object
dtypes: datetime64[ns, UTC](1), float32(3), int32(2), object(1), string(4)
memory usage: 20.1+ KB

c:\Users\lamin\OneDrive\Documents\Maitrise en info Canada\ASTD project\TrackBuilder\track_builder\core\io_helpers.py:142: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  df["month"] = df["date_time_utc"].dt.to_period("M").astype(str)

In [9]:
# --- Setup ---
print(f"--- Loading the full year 2019 ---\n")

# --- Action ---
df_full_year = tb.load_astd_monthly(sample_data_path, year=2019)

# --- Verification ---
# The resulting DataFrame should contain 1200 rows.
df_full_year.info()

--- Loading the full year 2019 ---

Loading ASTD CSVs: 100%|██████████| 12/12 [00:00<00:00, 154.61it/s]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   shipid          1200 non-null   int32
 1   date_time_utc   1200 non-null   datetime64[ns, UTC]
 2   flagname        299 non-null    string
 3   iceclass        0 non-null      string
 4   astd_cat        1200 non-null   string
 5   sizegroup_gt    299 non-null    string
 6   dist_nextpoint  1050 non-null   float32
 7   sec_nextpoint   1200 non-null   int32
 8   longitude       1200 non-null   float32
 9   latitude        1200 non-null   float32
 10  month           1200 non-null   object
dtypes: datetime64[ns, UTC](1), float32(3), int32(2), object(1), string(4)
memory usage: 79.8+ KB

c:\Users\lamin\OneDrive\Documents\Maitrise en info Canada\ASTD project\TrackBuilder\track_builder\core\io_helpers.py:143: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  df["month"] = df["date_time_utc"].dt.to_period("M").astype(str)