In [1]:
import sys
import os




project_path = r"C:\Users\lamin\Documents\maitrise\ASTD\TrackBuilder"
if project_path not in sys.path:
    sys.path.append(project_path)

import track_builder as tb

import pandas as pd
import track_builder as tb

import os
from dotenv import load_dotenv

load_dotenv()

saving_path = os.getenv("SAVING")
track_output_path = os.path.join(saving_path, "tracks")
df_output_path = os.path.join(saving_path, "df")
os.makedirs(track_output_path, exist_ok=True)
os.makedirs(df_output_path, exist_ok=True)

BASE_PATH = r"C:\Users\lamin\Documents\maitrise\ASTD\data"
YEAR      = 2019

MONTHS_TO_LOAD = [1, 2, 3, 4, 5]

USECOLS   = "default"
SAMPLING  = [0, -1]

COLS_REQUIRED = [
    "shipid",
    "date_time_utc",
    "latitude",
    "longitude",
    "astd_cat",
    "flagname",
    "iceclass",
    "sizegroup_gt"
]

In [2]:
df_parquet_file = os.path.join(df_output_path, "first_and_last_of_5month_astd_data.parquet")

if os.path.exists(df_parquet_file):
    df_for_track = pd.read_parquet(df_parquet_file)
else:
    df_for_track = tb.load_astd_monthly(
        BASE_PATH, YEAR, months=MONTHS_TO_LOAD, progress=True,
        usecols=USECOLS, sampling=SAMPLING, remove_nan_rows=COLS_REQUIRED
    )

    
    df_for_track.to_parquet(df_parquet_file, index=False)

In [3]:
df_for_track

,shipid,date_time_utc,flagname,iceclass,astd_cat,sizegroup_gt,dist_nextpoint,sec_nextpoint,longitude,latitude
0,5966,2019-01-01 00:00:02+00:00,Russia,FS Ice Class 1A,General cargo ships,10000 - 24999,616.758301,971,72.985146,73.034294
1,3768,2019-01-01 00:00:02+00:00,Netherlands,FS Ice Class 1C,Other service offshore vessels,10000 - 24999,0.000000,718,7.734500,63.110500
2,3994,2019-01-01 00:00:02+00:00,Norway,FS Ice Class 1C,Offshore supply ships,1000 - 4999 GT,8.541162,371,5.850370,62.335602
3,1892,2019-01-01 00:00:04+00:00,Russia,FS Ice Class 1C,Fishing vessels,< 1000 GT,1.028629,540,29.700306,70.626442
4,3009,2019-01-01 00:00:04+00:00,Norway,FS Ice Class 1C,Fishing vessels,< 1000 GT,1945.192749,371,25.147583,70.990837
...,...,...,...,...,...,...,...,...,...,...
1241047,9692,2019-05-31 23:59:57+00:00,Antigua & Barbuda,FS Ice Class 1C,General cargo ships,1000 - 4999 GT,23.340099,360,28.317116,61.062233
1241048,2614,2019-05-31 23:59:57+00:00,Finland,FS Ice Class 1C,Passenger ships,< 1000 GT,0.187196,899,21.367895,59.786774
1241049,14132,2019-05-31 23:59:58+00:00,Antigua & Barbuda,FS Ice Class 1B,General cargo ships,1000 - 4999 GT,1889.382202,371,28.358707,62.132450
1241050,5980,2019-05-31 23:59:58+00:00,Norway,FS Ice Class 1C,General cargo ships,1000 - 4999 GT,2183.170410,370,14.922500,68.239670
1241051,5229,2019-05-31 23:59:58+00:00,Sweden,FS Ice Class 1A,Ro-Ro cargo ships,10000 - 24999,0.250567,361,19.155767,63.322342

In [4]:
df_parquet_file2 = os.path.join(df_output_path, "all5month_astd_data2_without_nan_col.parquet")

if os.path.exists(df_parquet_file2):
    df = pd.read_parquet(df_parquet_file2)
else:
    df = tb.load_astd_monthly(
        BASE_PATH, YEAR, months=MONTHS_TO_LOAD, progress=True,
        usecols=USECOLS, sampling=None, remove_nan_rows=COLS_REQUIRED
    )
    
    df.to_parquet(df_parquet_file2, index=False)

df

,shipid,date_time_utc,flagname,iceclass,astd_cat,sizegroup_gt,dist_nextpoint,sec_nextpoint,longitude,latitude
0,5966,2019-01-01 00:00:02+00:00,Russia,FS Ice Class 1A,General cargo ships,10000 - 24999,616.758301,971,72.985146,73.034294
1,3994,2019-01-01 00:00:02+00:00,Norway,FS Ice Class 1C,Offshore supply ships,1000 - 4999 GT,8.541162,371,5.850370,62.335602
2,3768,2019-01-01 00:00:02+00:00,Netherlands,FS Ice Class 1C,Other service offshore vessels,10000 - 24999,0.000000,718,7.734500,63.110500
3,1892,2019-01-01 00:00:04+00:00,Russia,FS Ice Class 1C,Fishing vessels,< 1000 GT,1.028629,540,29.700306,70.626442
4,3009,2019-01-01 00:00:04+00:00,Norway,FS Ice Class 1C,Fishing vessels,< 1000 GT,1945.192749,371,25.147583,70.990837
...,...,...,...,...,...,...,...,...,...,...
18081637,2614,2019-05-31 23:59:57+00:00,Finland,FS Ice Class 1C,Passenger ships,< 1000 GT,0.187196,899,21.367895,59.786774
18081638,3409,2019-05-31 23:59:57+00:00,Iceland,FS Ice Class 1C,Fishing vessels,1000 - 4999 GT,1.704260,350,-20.276325,63.446232
18081639,14132,2019-05-31 23:59:58+00:00,Antigua & Barbuda,FS Ice Class 1B,General cargo ships,1000 - 4999 GT,1889.382202,371,28.358707,62.132450
18081640,5229,2019-05-31 23:59:58+00:00,Sweden,FS Ice Class 1A,Ro-Ro cargo ships,10000 - 24999,0.250567,361,19.155767,63.322342
18081641,5980,2019-05-31 23:59:58+00:00,Norway,FS Ice Class 1C,General cargo ships,1000 - 4999 GT,2183.170410,370,14.922500,68.239670

In [22]:
df_preprocessing = tb.remove_unrealistic_points(df, multiplier=3.0)

computing typical speeds...

C:\Users\lamin\Documents\maitrise\ASTD\TrackBuilder\track_builder\core\track_helpers.py:358: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

C:\Users\lamin\Documents\maitrise\ASTD\TrackBuilder\track_builder\core\track_helpers.py:166: FutureWarning:

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

Cleaning completed: 7407 'ghost' or aberrant points removed.

In [12]:
# verify if .parquet file exists, if yes load it, else build tracks and save it
parquet_file_path = os.path.join(track_output_path, "tracks_2019_for_5_month.parquet")

if os.path.exists(parquet_file_path):
    tracks = pd.read_parquet(parquet_file_path)
else:
    tracks = tb.build_ship_tracks(df_for_track,
                                  max_time_gap_hours=25,
                                  max_distance_km=400,
                                  min_track_length=1,
                                  matching_strategy="balanced",
                                  )
    tracks.to_parquet(parquet_file_path)

tracks

        month  segment_id  track_id
0     2019-01        5966         1
1     2019-01        3768         2
2     2019-01        3994         3
3     2019-01        1892         4
4     2019-01        3009         5
...       ...         ...       ...
3990  2019-05        7601      2913
3991  2019-05       15938      2914
3992  2019-05        4535      2915
3993  2019-05        9630      2916
3994  2019-05       13583      2917

[3995 rows x 3 columns]

In [13]:
# tracks that span at least 3 months
month_counts = tracks.groupby("track_id")["month"].nunique()
multi_month_ids = month_counts[month_counts >= 3].index

print("Number of tracks spanning at least 3 months:", len(multi_month_ids))
tracks[tracks["track_id"].isin(multi_month_ids)].head(10)

Number of tracks spanning at least 3 months: 162

      month  segment_id  track_id
6   2019-01        1541         6
7   2019-02        1418         6
8   2019-03        1602         6
12  2019-01        2424        10
13  2019-02        2258        10
14  2019-03        2454        10
50  2019-01        2419        38
51  2019-02        2253        38
52  2019-03        2449        38
81  2019-01        5954        63

In [14]:
# tracks that span at least 5 months
month_counts = tracks.groupby("track_id")["month"].nunique()
multi_month_ids = month_counts[month_counts >= 5].index

print("Number of tracks spanning at least 5 months:", len(multi_month_ids))
tracks[tracks["track_id"].isin(multi_month_ids)].head(10)

Number of tracks spanning at least 5 months: 10

       month  segment_id  track_id
225  2019-01        1864       180
226  2019-02        1735       180
227  2019-03        1926       180
228  2019-04        2597       180
229  2019-05        2072       180
294  2019-01         146       228
295  2019-02         137       228
296  2019-03         158       228
297  2019-04         747       228
298  2019-05         236       228

In [15]:
# Without preprocessing 

work = tb.build_light_multi_track_data(track_table=tracks, track_sampling=20, positions_df=df, n_tracks_length=5, preprocess_positions=False)

fig = tb.plot_ship_tracks(
    work,
    color_by="track_id",
    color_mode="categorical",
    show_points=False,
    map_style="open-street-map",
    title="Tracks (light multi-track sample)",
)
fig.update_layout(showlegend=False)
fig.show()

C:\Users\lamin\Documents\maitrise\ASTD\TrackBuilder\track_builder\io\astd_loader.py:501: FutureWarning:

DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.

In [20]:

work = tb.build_light_multi_track_data(track_table=tracks, track_sampling=20, positions_df=df_preprocessing, n_tracks_length=5, preprocess_positions=False)

fig = tb.plot_ship_tracks(
    work,
    color_by="track_id",
    color_mode="categorical",
    show_points=False,
    map_style="open-street-map",
    title="Tracks (light multi-track sample)",
)
fig.update_layout(showlegend=False)
fig.show()

C:\Users\lamin\Documents\maitrise\ASTD\TrackBuilder\track_builder\io\astd_loader.py:501: FutureWarning:

DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.