In [1]:
import sys
import os




project_path = r"C:\Users\lamin\Documents\maitrise\ASTD\TrackBuilder"
if project_path not in sys.path:
    sys.path.append(project_path)

import track_builder as tb

import pandas as pd
import track_builder as tb

import os
from dotenv import load_dotenv

load_dotenv()

saving_path = os.getenv("SAVING")
track_output_path = os.path.join(saving_path, "tracks")
df_output_path = os.path.join(saving_path, "df")
os.makedirs(track_output_path, exist_ok=True)
os.makedirs(df_output_path, exist_ok=True)

BASE_PATH = r"C:\Users\lamin\Documents\maitrise\ASTD\data"
YEAR      = 2019

MONTHS_TO_LOAD = [1, 2, 3]

USECOLS   = "default"
SAMPLING  = [0, -1]

COLS_REQUIRED = [
    "shipid",
    "date_time_utc",
    "latitude",
    "longitude",
    "astd_cat",
    "flagname",
    "iceclass",
    "sizegroup_gt"
]

In [2]:
df_parquet_file = os.path.join(df_output_path, "first_and_last_of_3month_astd_data2.parquet")

if os.path.exists(df_parquet_file):
    df = pd.read_parquet(df_parquet_file)
else:
    df = tb.load_astd_monthly(
        BASE_PATH, YEAR, months=MONTHS_TO_LOAD, progress=True,
        usecols=USECOLS, sampling=SAMPLING, remove_nan_rows=COLS_REQUIRED
    )

    
    df.to_parquet(df_parquet_file, index=False)

In [3]:
df

,shipid,date_time_utc,flagname,iceclass,astd_cat,sizegroup_gt,dist_nextpoint,sec_nextpoint,longitude,latitude
0,3994,2019-01-01 00:00:02+00:00,Norway,FS Ice Class 1C,Offshore supply ships,1000 - 4999 GT,8.541162,371,5.850370,62.335602
1,3768,2019-01-01 00:00:02+00:00,Netherlands,FS Ice Class 1C,Other service offshore vessels,10000 - 24999,0.000000,718,7.734500,63.110500
2,5966,2019-01-01 00:00:02+00:00,Russia,FS Ice Class 1A,General cargo ships,10000 - 24999,616.758301,971,72.985146,73.034294
3,3009,2019-01-01 00:00:04+00:00,Norway,FS Ice Class 1C,Fishing vessels,< 1000 GT,1945.192749,371,25.147583,70.990837
4,1892,2019-01-01 00:00:04+00:00,Russia,FS Ice Class 1C,Fishing vessels,< 1000 GT,1.028629,540,29.700306,70.626442
...,...,...,...,...,...,...,...,...,...,...
736701,3564,2019-03-31 23:59:50+00:00,Norway (Nis),FS Ice Class 1A,Chemical tankers,10000 - 24999,2302.299072,359,23.933922,65.186638
736702,5021,2019-03-31 23:59:53+00:00,Russia,FS Ice Class 1A,Chemical tankers,1000 - 4999 GT,1870.320190,369,12.534060,68.958694
736703,2247,2019-03-31 23:59:53+00:00,Finland,FS Ice Class 1A Super,Passenger ships,25000 - 49999,7046.579590,726,21.350834,59.574165
736704,5018,2019-03-31 23:59:57+00:00,Liberia,FS Ice Class II,Refrigerated cargo ships,10000 - 24999,2.131150,540,-6.841878,62.049644
736705,20554,2019-03-31 23:59:57+00:00,Antigua & Barbuda,FS Ice Class 1A,General cargo ships,1000 - 4999 GT,1981.756470,370,6.620860,63.038258

In [4]:
df_parquet_file2 = os.path.join(df_output_path, "all3month_astd_data2_without_nan_col.parquet")

if os.path.exists(df_parquet_file2):
    df = pd.read_parquet(df_parquet_file2)
else:
    df = tb.load_astd_monthly(
        BASE_PATH, YEAR, months=MONTHS_TO_LOAD, progress=True,
        usecols=USECOLS, sampling=None, remove_nan_rows=COLS_REQUIRED
    )
    
    df.to_parquet(df_parquet_file2, index=False)

df

,shipid,date_time_utc,flagname,iceclass,astd_cat,sizegroup_gt,dist_nextpoint,sec_nextpoint,longitude,latitude
0,5966,2019-01-01 00:00:02+00:00,Russia,FS Ice Class 1A,General cargo ships,10000 - 24999,616.758301,971,72.985146,73.034294
1,3994,2019-01-01 00:00:02+00:00,Norway,FS Ice Class 1C,Offshore supply ships,1000 - 4999 GT,8.541162,371,5.850370,62.335602
2,3768,2019-01-01 00:00:02+00:00,Netherlands,FS Ice Class 1C,Other service offshore vessels,10000 - 24999,0.000000,718,7.734500,63.110500
3,1892,2019-01-01 00:00:04+00:00,Russia,FS Ice Class 1C,Fishing vessels,< 1000 GT,1.028629,540,29.700306,70.626442
4,3009,2019-01-01 00:00:04+00:00,Norway,FS Ice Class 1C,Fishing vessels,< 1000 GT,1945.192749,371,25.147583,70.990837
...,...,...,...,...,...,...,...,...,...,...
10718047,3095,2019-03-31 23:59:50+00:00,Finland,FS Ice Class 1A,General cargo ships,1000 - 4999 GT,3.344720,341,17.491156,62.506004
10718048,2247,2019-03-31 23:59:53+00:00,Finland,FS Ice Class 1A Super,Passenger ships,25000 - 49999,7046.579590,726,21.350834,59.574165
10718049,5021,2019-03-31 23:59:53+00:00,Russia,FS Ice Class 1A,Chemical tankers,1000 - 4999 GT,1870.320190,369,12.534060,68.958694
10718050,5018,2019-03-31 23:59:57+00:00,Liberia,FS Ice Class II,Refrigerated cargo ships,10000 - 24999,2.131150,540,-6.841878,62.049644
10718051,20554,2019-03-31 23:59:57+00:00,Antigua & Barbuda,FS Ice Class 1A,General cargo ships,1000 - 4999 GT,1981.756470,370,6.620860,63.038258

In [5]:
all3month_parquet_file = os.path.join(df_output_path, "dataframes3month_astd_data.parquet")
df_all3month = pd.read_parquet(all3month_parquet_file)

df_all3month

,shipid,date_time_utc,flagname,iceclass,astd_cat,sizegroup_gt,dist_nextpoint,sec_nextpoint,longitude,latitude
0,1645,2019-01-01 00:00:00+00:00,Iceland,NaN,Fishing vessels,< 1000 GT,0.731465,361,-23.703033,64.896217
1,162,2019-01-01 00:00:00+00:00,Iceland,NaN,Unknown,NaN,2.242847,209,-21.827280,64.134209
2,3619,2019-01-01 00:00:00+00:00,Norway,NaN,Other activities,1000 - 4999 GT,491.440918,369,14.545295,68.205574
3,2490,2019-01-01 00:00:00+00:00,Iceland,NaN,Fishing vessels,1000 - 4999 GT,2.241636,82,-23.127956,66.069336
4,2778,2019-01-01 00:00:01+00:00,Cyprus,NaN,Other activities,1000 - 4999 GT,1.755199,539,25.198217,60.221077
...,...,...,...,...,...,...,...,...,...,...
31410007,20554,2019-03-31 23:59:57+00:00,Antigua & Barbuda,FS Ice Class 1A,General cargo ships,1000 - 4999 GT,1981.756470,370,6.620860,63.038258
31410008,5018,2019-03-31 23:59:57+00:00,Liberia,FS Ice Class II,Refrigerated cargo ships,10000 - 24999,2.131150,540,-6.841878,62.049644
31410009,1998,2019-03-31 23:59:57+00:00,Iceland,NaN,Passenger ships,< 1000 GT,3.325421,281,-22.725639,65.078285
31410010,1008,2019-03-31 23:59:57+00:00,Sweden,NaN,Unknown,NaN,1159.941895,279,17.816191,60.908493
31410011,2277,2019-03-31 23:59:58+00:00,Faeroe Islands,NaN,Fishing vessels,< 1000 GT,1746.223877,360,-5.327251,62.258442

In [6]:
#preprocessing
df_preprocessing = tb.remove_unrealistic_points(df)

computing typical speeds...

C:\Users\lamin\Documents\maitrise\ASTD\TrackBuilder\track_builder\core\track_helpers.py:358: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  out = (ship_means.groupby('astd_cat')
C:\Users\lamin\Documents\maitrise\ASTD\TrackBuilder\track_builder\core\track_helpers.py:166: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  valid_bwd = valid_fwd.shift(1).fillna(False) & is_same_ship_prev

Cleaning completed: 696955 'ghost' or aberrant points removed.

In [7]:
df_preprocessing

,shipid,date_time_utc,flagname,iceclass,astd_cat,sizegroup_gt,dist_nextpoint,sec_nextpoint,longitude,latitude
3699862,137,2019-02-01 00:05:22+00:00,Iceland,FS Ice Class 1C,Fishing vessels,< 1000 GT,1.443724,19,-23.703388,64.895935
3699881,137,2019-02-01 00:05:41+00:00,Iceland,FS Ice Class 1C,Fishing vessels,< 1000 GT,0.926142,370,-23.703411,64.895927
3700472,137,2019-02-01 00:11:51+00:00,Iceland,FS Ice Class 1C,Fishing vessels,< 1000 GT,0.942409,331,-23.703400,64.895935
3700971,137,2019-02-01 00:17:23+00:00,Iceland,FS Ice Class 1C,Fishing vessels,< 1000 GT,1.080970,29,-23.703396,64.895927
3701019,137,2019-02-01 00:17:51+00:00,Iceland,FS Ice Class 1C,Fishing vessels,< 1000 GT,1.721536,341,-23.703409,64.895920
...,...,...,...,...,...,...,...,...,...,...
2475775,24347,2019-01-21 22:41:17+00:00,Antigua & Barbuda,FS Ice Class II,General cargo ships,1000 - 4999 GT,2058.947510,369,21.316895,59.625397
2476242,24347,2019-01-21 22:47:26+00:00,Antigua & Barbuda,FS Ice Class II,General cargo ships,1000 - 4999 GT,2962.419678,540,21.312836,59.607029
2476974,24347,2019-01-21 22:56:26+00:00,Antigua & Barbuda,FS Ice Class II,General cargo ships,1000 - 4999 GT,5250.390625,939,21.305248,59.580719
2478234,24347,2019-01-21 23:12:04+00:00,Antigua & Barbuda,FS Ice Class II,General cargo ships,1000 - 4999 GT,2008.941040,361,21.269367,59.537251
2478685,24347,2019-01-21 23:18:06+00:00,Antigua & Barbuda,FS Ice Class II,General cargo ships,1000 - 4999 GT,3994.003418,720,21.255997,59.520546

In [8]:
# verify if .parquet file exists, if yes load it, else build tracks and save it
parquet_file_path = os.path.join(track_output_path, "tracks_2019_1.parquet")

if os.path.exists(parquet_file_path):
    tracks = pd.read_parquet(parquet_file_path)
else:
    tracks = tb.build_ship_tracks(df,
                                  max_time_gap_hours=25,
                                  max_distance_km=400,
                                  min_track_length=1,
                                  matching_strategy="balanced",
                                  )
    tracks.to_parquet(parquet_file_path)

tracks

        month  segment_id  track_id
0     2019-01        3994         1
1     2019-01        3768         2
2     2019-01        5966         3
3     2019-02        2903         3
4     2019-03        3125         3
...       ...         ...       ...
2613  2019-03       20535      1933
2614  2019-03        5113      1934
2615  2019-03        6483      1935
2616  2019-03       20546      1936
2617  2019-03        5736      1937

[2618 rows x 3 columns]

In [8]:
tb.get_track_statistics(tracks, df)

{'n_tracks': 1937,
 'n_segments': 2618,
 'avg_length': 1.3515745998967474,
 'max_length': 3,
 'lengths': track_id
 1       1
 2       1
 3       3
 4       2
 5       1
        ..
 1933    1
 1934    1
 1935    1
 1936    1
 1937    1
 Length: 1937, dtype: int64,
 'by_month': month
 2019-01    1005
 2019-02     868
 2019-03     745
 dtype: int64,
 'by_ship_type': astd_cat
 general cargo ships               779
 fishing vessels                   694
 chemical tankers                  209
 container ships                   172
 other activities                  161
 passenger ships                   119
 bulk carriers                     111
 ro-ro cargo ships                 104
 offshore supply ships              80
 refrigerated cargo ships           58
 oil product tankers                48
 crude oil tankers                  37
 other service offshore vessels     19
 gas tankers                        16
 cruise ships                       11
 Name: count, dtype: int64}

In [9]:
# tracks that span at least 2 months
month_counts = tracks.groupby("track_id")["month"].nunique()
multi_month_ids = month_counts[month_counts >= 2].index

print("Number of tracks spanning at least 2 months:", len(multi_month_ids))
tracks[tracks["track_id"].isin(multi_month_ids)].head(10)

Number of tracks spanning at least 2 months: 567

      month  segment_id  track_id
2   2019-01        5966         3
3   2019-02        2903         3
4   2019-03        3125         3
5   2019-01        3009         4
6   2019-02        2858         4
8   2019-01        1541         6
9   2019-02        1418         6
10  2019-03        1602         6
13  2019-01        2424         9
14  2019-02        2258         9

In [10]:
# tracks that span at least 3 months
month_counts = tracks.groupby("track_id")["month"].nunique()
multi_month_ids = month_counts[month_counts >= 3].index

print("Number of tracks spanning at least 3 months:", len(multi_month_ids))
tracks[tracks["track_id"].isin(multi_month_ids)].head(10)

Number of tracks spanning at least 3 months: 114

      month  segment_id  track_id
2   2019-01        5966         3
3   2019-02        2903         3
4   2019-03        3125         3
8   2019-01        1541         6
9   2019-02        1418         6
10  2019-03        1602         6
13  2019-01        2424         9
14  2019-02        2258         9
15  2019-03        2454         9
17  2019-01        9019        11

In [11]:
# Without preprocessing 

work = tb.build_light_multi_track_data(track_table=tracks, track_sampling=20, positions_df=df, n_tracks_length=3,
                                       base_path=BASE_PATH, chunksize=500_000, progress=True, point_stride=10,
                                       random_state=42)

fig = tb.plot_ship_tracks(
    work,
    color_by="track_id",
    color_mode="categorical",
    show_points=False,
    map_style="open-street-map",
    title="Tracks (light multi-track sample)",
)
fig.update_layout(showlegend=False)
fig.show()

C:\Users\lamin\Documents\maitrise\ASTD\TrackBuilder\track_builder\io\astd_loader.py:432: FutureWarning:

DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.

In [9]:

work = tb.build_light_multi_track_data(track_table=tracks, track_sampling=20, positions_df=df_preprocessing, n_tracks_length=3,
                                       base_path=BASE_PATH, chunksize=500_000, progress=True, point_stride=10,
                                       random_state=42)

fig = tb.plot_ship_tracks(
    work,
    color_by="track_id",
    color_mode="categorical",
    show_points=False,
    map_style="open-street-map",
    title="Tracks (light multi-track sample)",
)
fig.update_layout(showlegend=False)
fig.show()

C:\Users\lamin\Documents\maitrise\ASTD\TrackBuilder\track_builder\io\astd_loader.py:432: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda g: g.iloc[::point_stride])