In [31]:
import sys
import os




project_path = r"C:\Users\lamin\Documents\maitrise\ASTD\TrackBuilder"
if project_path not in sys.path:
    sys.path.append(project_path)

import track_builder as tb

import pandas as pd
import track_builder as tb

import os
from dotenv import load_dotenv

load_dotenv()

saving_path = os.getenv("SAVING")
track_output_path = os.path.join(saving_path, "tracks")
df_output_path = os.path.join(saving_path, "df")
os.makedirs(track_output_path, exist_ok=True)
os.makedirs(df_output_path, exist_ok=True)

BASE_PATH = r"C:\Users\lamin\Documents\maitrise\ASTD\data"
YEAR      = 2019

MONTHS_TO_LOAD = [1, 2, 3, 4, 5, 7, 8, 9, 10, 11, 12]

USECOLS   = "default"
SAMPLING  = [0, -1]

COLS_REQUIRED = [
    "shipid",
    "date_time_utc",
    "latitude",
    "longitude",
    "astd_cat",
    "flagname",
    "iceclass",
    "sizegroup_gt"
]

In [32]:
df_parquet_file = os.path.join(df_output_path, "first_and_last_of_12month_astd_data.parquet")

if os.path.exists(df_parquet_file):
    df_for_track = pd.read_parquet(df_parquet_file)
else:
    df_for_track = tb.load_astd_monthly(
        BASE_PATH, YEAR, months=MONTHS_TO_LOAD, progress=True,
        usecols=USECOLS, sampling=SAMPLING, remove_nan_rows=COLS_REQUIRED
    )

    
    df_for_track.to_parquet(df_parquet_file, index=False)

In [33]:
df_for_track

,shipid,date_time_utc,flagname,iceclass,astd_cat,sizegroup_gt,dist_nextpoint,sec_nextpoint,longitude,latitude
0,3994,2019-01-01 00:00:02+00:00,Norway,FS Ice Class 1C,Offshore supply ships,1000 - 4999 GT,8.541162,371,5.850370,62.335602
1,5966,2019-01-01 00:00:02+00:00,Russia,FS Ice Class 1A,General cargo ships,10000 - 24999,616.758301,971,72.985146,73.034294
2,3768,2019-01-01 00:00:02+00:00,Netherlands,FS Ice Class 1C,Other service offshore vessels,10000 - 24999,0.000000,718,7.734500,63.110500
3,1541,2019-01-01 00:00:04+00:00,Norway (Nis),FS Ice Class 1C,Passenger ships,1000 - 4999 GT,0.000000,364,7.733963,63.113628
4,3009,2019-01-01 00:00:04+00:00,Norway,FS Ice Class 1C,Fishing vessels,< 1000 GT,1945.192749,371,25.147583,70.990837
...,...,...,...,...,...,...,...,...,...,...
2776998,3554,2019-12-31 23:59:55+00:00,Estonia,FS Ice Class 1A Super,Passenger ships,25000 - 49999,4287.122070,444,20.261957,59.774624
2776999,1858,2019-12-31 23:59:57+00:00,Russia,FS Ice Class 1C,Fishing vessels,1000 - 4999 GT,2.558345,361,30.023096,69.724503
2777000,3117,2019-12-31 23:59:57+00:00,Russia,FS Ice Class 1C,Fishing vessels,< 1000 GT,2.081501,535,30.040400,69.729546
2777001,10238,2019-12-31 23:59:58+00:00,Netherlands,FS Ice Class 1A,General cargo ships,1000 - 4999 GT,3.977488,174,-23.117926,66.067093
2777002,3063,2019-12-31 23:59:58+00:00,Norway,FS Ice Class 1C,Fishing vessels,1000 - 4999 GT,199.942719,36,19.658154,69.834648

In [34]:
df_parquet_file2 = os.path.join(df_output_path, "all12month_astd_data2_without_nan_col.parquet")

if os.path.exists(df_parquet_file2):
    df = pd.read_parquet(df_parquet_file2)
else:
    df = tb.load_astd_monthly(
        BASE_PATH, YEAR, months=MONTHS_TO_LOAD, progress=True,
        usecols=USECOLS, sampling=None, remove_nan_rows=COLS_REQUIRED
    )
    
    df.to_parquet(df_parquet_file2, index=False)

df

,shipid,date_time_utc,flagname,iceclass,astd_cat,sizegroup_gt,dist_nextpoint,sec_nextpoint,longitude,latitude
0,5966,2019-01-01 00:00:02+00:00,Russia,FS Ice Class 1A,General cargo ships,10000 - 24999,616.758301,971,72.985146,73.034294
1,3994,2019-01-01 00:00:02+00:00,Norway,FS Ice Class 1C,Offshore supply ships,1000 - 4999 GT,8.541162,371,5.850370,62.335602
2,3768,2019-01-01 00:00:02+00:00,Netherlands,FS Ice Class 1C,Other service offshore vessels,10000 - 24999,0.000000,718,7.734500,63.110500
3,1892,2019-01-01 00:00:04+00:00,Russia,FS Ice Class 1C,Fishing vessels,< 1000 GT,1.028629,540,29.700306,70.626442
4,3009,2019-01-01 00:00:04+00:00,Norway,FS Ice Class 1C,Fishing vessels,< 1000 GT,1945.192749,371,25.147583,70.990837
...,...,...,...,...,...,...,...,...,...,...
41449667,3554,2019-12-31 23:59:55+00:00,Estonia,FS Ice Class 1A Super,Passenger ships,25000 - 49999,4287.122070,444,20.261957,59.774624
41449668,3117,2019-12-31 23:59:57+00:00,Russia,FS Ice Class 1C,Fishing vessels,< 1000 GT,2.081501,535,30.040400,69.729546
41449669,1858,2019-12-31 23:59:57+00:00,Russia,FS Ice Class 1C,Fishing vessels,1000 - 4999 GT,2.558345,361,30.023096,69.724503
41449670,10238,2019-12-31 23:59:58+00:00,Netherlands,FS Ice Class 1A,General cargo ships,1000 - 4999 GT,3.977488,174,-23.117926,66.067093
41449671,3063,2019-12-31 23:59:58+00:00,Norway,FS Ice Class 1C,Fishing vessels,1000 - 4999 GT,199.942719,36,19.658154,69.834648

In [35]:
# Exemple de ce que vous avez probablement obtenu avec les 5 mois
# Copiez ces valeurs manuellement ou sauvegardez-les
WINTER_SPEEDS = {
    'fishing vessels': 11.08,
    'other service offshore vessels': 11.01,
    'other activities': 12.09,
    'offshore supply ships': 13.35,
    'refrigerated cargo ships': 16.77,
    'general cargo ships': 16.93,
    'oil product tankers': 19.30,
    'chemical tankers': 19.38,
    'bulk carriers': 19.85,
    'gas tankers': 20.56,
    'crude oil tankers': 20.71,
    'cruise ships': 21.65,
    'ro-ro cargo ships': 25.22,
    'passenger ships': 27.51,
    'container ships': 29.91
}

In [36]:
# verify if .parquet file exists, if yes load it, else build tracks and save it
parquet_file_path = os.path.join(track_output_path, "tracks_2019_for_12_month_with_winter_speeds.parquet")

if os.path.exists(parquet_file_path):
    tracks = pd.read_parquet(parquet_file_path)
else:
    tracks, logs = tb.build_ship_tracks(df_for_track,
                                  max_time_gap_hours=25,
                                  max_distance_km=400,
                                  min_track_length=1,
                                  matching_strategy="balanced",
                                  return_logs=True,
                                  )
    tracks.to_parquet(parquet_file_path)

tracks

         month  segment_id  track_id
0      2019-01        3768         1
1      2019-01        3994         2
2      2019-02        3742         2
3      2019-03        4018         2
4      2019-04        4705         2
...        ...         ...       ...
12152  2019-12        7261      5983
12153  2019-12        7656      5984
12154  2019-12       10500      5985
12155  2019-12       10921      5986
12156  2019-12       10130      5987

[12157 rows x 3 columns]

In [37]:
logs

,match_id,from_shipid,to_shipid,from_month,to_month,stage,reason,dt_hours,distance_km_fd,implied_v_kmh
0,3768→18256,3768.0,18256.0,2019-01,2019-02,filter,time_window,720.104722,107.109657,NaN
1,3768→3641,3768.0,3641.0,2019-01,2019-02,filter,time_window,720.199167,1099.618164,NaN
2,3768→3770,3768.0,3770.0,2019-01,2019-02,filter,time_window,720.214722,99.916710,NaN
3,3768→2844,3768.0,2844.0,2019-01,2019-02,filter,time_window,720.220000,228.794662,NaN
4,3768→18432,3768.0,18432.0,2019-01,2019-02,filter,time_window,721.145556,66.224602,NaN
...,...,...,...,...,...,...,...,...,...,...
12466070,16250→2964,16250.0,2964.0,2019-11,2019-12,filter,flagname_mismatch,20.496111,283.522644,13.832997
12466071,16250→3323,16250.0,3323.0,2019-11,2019-12,filter,flagname_mismatch,20.776944,224.430695,10.801911
12466072,16250→2997,16250.0,2997.0,2019-11,2019-12,filter,flagname_mismatch,21.343611,10.478917,0.490963
12466073,16250→4195,16250.0,4195.0,2019-11,2019-12,filter,flagname_mismatch,22.254722,251.095917,11.282815
12466074,16250→3052,16250.0,3052.0,2019-11,2019-12,filter,astd_cat_mismatch,4.101389,15.590671,3.801315

In [38]:
problem_logs = logs[(logs['from_shipid'] == 4078.0) & (logs['from_month'] == "2019-01") & (logs['to_shipid'] == 3821.0) & (logs['to_month'] == "2019-02")]

problem_logs

Empty DataFrame
Columns: [match_id, from_shipid, to_shipid, from_month, to_month, stage, reason, dt_hours, distance_km_fd, implied_v_kmh]
Index: []

In [39]:
# tracks that span at least 3 months
month_counts = tracks.groupby("track_id")["month"].nunique()
multi_month_ids = month_counts[month_counts == 5].index

print("Number of tracks spanning at least 5 months for 12 months of data:", len(multi_month_ids))
tracks[tracks["track_id"].isin(multi_month_ids)].head(10)

Number of tracks spanning at least 5 months for 12 months of data: 321

      month  segment_id  track_id
1   2019-01        3994         2
2   2019-02        3742         2
3   2019-03        4018         2
4   2019-04        4705         2
5   2019-05        4311         2
6   2019-01        5966         3
7   2019-02        2903         3
8   2019-03        3125         3
9   2019-04        5641         3
10  2019-05        3387         3

In [ ]:
# tracks that span at least 5 months
month_counts = tracks.groupby("track_id")["month"].nunique()
multi_month_ids = month_counts[month_counts >= 6].index

print("Number of tracks spanning at least 5 months:", len(multi_month_ids))
tracks[tracks["track_id"].isin(multi_month_ids)].head(10)

In [ ]:
# Voir la distribution des longueurs de tracks
print(tracks.groupby("track_id")["month"].nunique().value_counts().sort_index())

In [ ]:
# tb.compute_typical_speeds_by_astd_cat(df)

In [ ]:
# Without preprocessing 

work = tb.build_light_multi_track_data(track_table=tracks, track_sampling=10, positions_df=df, n_tracks_length=6, preprocess_positions=False)

fig = tb.plot_ship_tracks(
    work,
    color_by="track_id",
    color_mode="categorical",
    show_points=False,
    map_style="open-street-map",
    title="Tracks (light multi-track sample)",
)
fig.update_layout(showlegend=False)
fig.show()

In [ ]:

work = tb.build_light_multi_track_data(track_table=tracks, track_sampling=10, positions_df=df, n_tracks_length=6, preprocess_positions=True)

fig = tb.plot_ship_tracks(
    work,
    color_by="track_id",
    color_mode="categorical",
    show_points=False,
    map_style="open-street-map",
    title="Tracks (light multi-track sample)",
)
fig.update_layout(showlegend=False)
fig.show()

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# ---------------------------------------------------------
# 1. PRÉPARATION : Récupérer les infos navires (Type, etc.)
# ---------------------------------------------------------
# On a besoin de savoir quel type de navire correspond à chaque track_id.
# On prend le type associé au premier segment de chaque track.

# Création d'un dictionnaire {shipid: astd_cat} à partir des données brutes
# (On prend le premier 'astd_cat' trouvé pour chaque navire pour être efficace)
ship_info = df.drop_duplicates('shipid')[['shipid', 'astd_cat']].set_index('shipid')

# On joint ces infos à notre table de tracks
# Note : dans votre code corrigé, segment_id = shipid
tracks_enriched = tracks.merge(
    ship_info, 
    left_on='segment_id', 
    right_index=True, 
    how='left'
)

# ---------------------------------------------------------
# 2. STATISTIQUE A : Durée de présence (Fidélité)
# ---------------------------------------------------------
# Combien de mois chaque navire reste-t-il dans l'Arctique ?
track_durations = tracks_enriched.groupby('track_id')['month'].nunique()

print("\n--- A. DISTRIBUTION DES DURÉES (en mois) ---")
dist_duration = track_durations.value_counts().sort_index()
print(dist_duration)

# ---------------------------------------------------------
# 3. STATISTIQUE B : Saisonnalité (Activité)
# ---------------------------------------------------------
# Combien de tracks actives y a-t-il par mois ?
# Attention : il faut trier les mois correctement (Jan, Fév, Mars...)
tracks_per_month = tracks_enriched.groupby('month')['track_id'].nunique().sort_index()

print("\n--- B. SAISONNALITÉ (Nb de tracks actives par mois) ---")
print(tracks_per_month)

# ---------------------------------------------------------
# 4. STATISTIQUE C : Répartition par Type (Composition)
# ---------------------------------------------------------
# Quels sont les types de navires qui font des tracks de 6 mois ou plus ?
long_tracks = tracks_enriched[tracks_enriched['track_id'].isin(track_durations[track_durations >= 6].index)]
# On compte chaque track unique une seule fois
type_counts_long = long_tracks.drop_duplicates('track_id')['astd_cat'].value_counts()

print("\n--- C. TYPES DE NAVIRES (Tracks >= 6 mois uniquement) ---")
print(type_counts_long.head(10))

In [ ]:
track_2928 = tb.load_track_data(track_ids=2928, track_table=tracks, base_path=BASE_PATH, chunksize=500_000)

In [ ]:
fig_track_2928 = tb.plot_individual_track(
        track_id=2928,
        track_table=tracks,
        astd_data=track_2928,
        show_segments=True,
        map_style="open-street-map",
        title=f"Track {2928}",
    )
    
fig_track_2928.show()

In [40]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# ---------------------------------------------------------
# 1. Préparation & Échantillonnage (La clé de la performance)
# ---------------------------------------------------------
# On reprend df_for_track (ou df)
df_viz_all = df_for_track.copy()

# On s'assure d'avoir la colonne mois
if 'month' not in df_viz_all.columns:
    df_viz_all['month'] = df_viz_all['date_time_utc'].dt.to_period('M').astype(str)
else:
    df_viz_all['month'] = df_viz_all['month'].astype(str)

# Création de la colonne Saison
def get_season(m):
    try:
        month_int = int(str(m).split('-')[1])
        if month_int in [1, 2, 3]: return 'Hiver'
        if month_int in [7, 8, 9]: return 'Été'
    except:
        pass
    return 'Autre'

df_viz_all['season'] = df_viz_all['month'].apply(get_season)

# Filtrer pour Hiver/Été uniquement
df_contrast_all = df_viz_all[df_viz_all['season'].isin(['Hiver', 'Été'])]

# --- C'EST ICI QUE TOUT CHANGE ---
# On ne garde qu'un point sur 20 (5% des données).
# C'est suffisant pour une heatmap et ça ne fera pas planter l'affichage.
SAMPLE_RATE = 20 
df_plot = df_contrast_all.iloc[::SAMPLE_RATE] 

print(f"Points originaux : {len(df_contrast_all)}")
print(f"Points affichés (1/{SAMPLE_RATE}) : {len(df_plot)}")
# ---------------------------------------------------------

df_hiver = df_plot[df_plot['season'] == 'Hiver']
df_ete = df_plot[df_plot['season'] == 'Été']

# 2. Génération de la Carte
fig = make_subplots(
    rows=1, cols=2,
    subplot_titles=(f"Hiver (n={len(df_hiver)})", f"Été (n={len(df_ete)})"),
    specs=[[{"type": "mapbox"}, {"type": "mapbox"}]]
)

# Carte Hiver
fig.add_trace(
    go.Densitymapbox(
        lat=df_hiver['latitude'],
        lon=df_hiver['longitude'],
        radius=8, # On augmente un peu le rayon car on a moins de points
        z=None,   
        colorscale='Viridis',
        showscale=False,
    ),
    row=1, col=1
)

# Carte Été
fig.add_trace(
    go.Densitymapbox(
        lat=df_ete['latitude'],
        lon=df_ete['longitude'],
        radius=8,
        z=None,
        colorscale='Viridis',
        showscale=True,
    ),
    row=1, col=2
)

# Style
common_map = dict(style="carto-positron", center=dict(lat=70, lon=20), zoom=1.5)
fig.update_layout(
    mapbox=common_map,
    mapbox2=common_map,
    title_text="Comparaison Globale (Échantillonnée) : Hiver vs Été",
    margin={"r":0,"t":50,"l":0,"b":0},
    showlegend=False
)

fig.show()

C:\Users\lamin\AppData\Local\Temp\ipykernel_19672\3102705890.py:12: UserWarning:

Converting to PeriodArray/Index representation will drop timezone information.

Points originaux : 1525239
Points affichés (1/20) : 76262

C:\Users\lamin\AppData\Local\Temp\ipykernel_19672\3102705890.py:53: DeprecationWarning:

*densitymapbox* is deprecated! Use *densitymap* instead. Learn more at: https://plotly.com/python/mapbox-to-maplibre/

C:\Users\lamin\AppData\Local\Temp\ipykernel_19672\3102705890.py:66: DeprecationWarning:

*densitymapbox* is deprecated! Use *densitymap* instead. Learn more at: https://plotly.com/python/mapbox-to-maplibre/